### ISSUE TITLE
create a Swift 2 cocoapod version so that it can be used as a dependency

### ISSUE THREAD

**Issue by evermeer** [kishikawakatsumi/KeychainAccess#105]
Currently I'm not able to create a Swift 2 version of my library because i have a dependency with KeychainAccess.

**Comment by AndrewBarba** [comment]
```
    pod 'KeychainAccess', :git => 'https://github.com/kishikawakatsumi/KeychainAccess.git', :branch => 'swift-2.0'
```

**Comment by evermeer** [comment]
That does not work when you have a library with a dependency to KeychainAccess and you are using that library in another library.  Then you can only setup the dependency in your .podspec file. In a .podspec file you can only set a specific version as a dependency. not a branch. 

In my situation I am using KeychainAccess in my AlamofireOauth2 project. Indeed in the Podfile I have set it up the way you mentioned above. That project builds and compiles fine. But I also have a project called EVWordpressAPI which has AlomifireOauth2 as a dependency. So KeychainAccess is not a direct dependency. Cocoapods will look in the .podspec for the dependencies, It will find KeychainAccess and it will add the version that is specified. The Swift2 branch does not have a cocoapod version yet.

**Comment by AndrewBarba** [comment]
It does work, I am also creating a Pod that is currently written in Swift 2.0 and it is using KeychainAccess on the swift-2.0 branch. I should have been more specific, it needs to be setup like so...
In your `.podspec` for your pod you should have some dependencies or sub dependencies like:
```
s.subspec "Core" do |core|
    core.source_files = 'Source/Core/**/*.swift'
    core.dependency 'Alamofire'
    core.dependency 'KeychainAccess'
    core.dependency 'ObjectMapper'
    core.dependency 'RealmSwift'
    core.dependency 'Starscream'
    core.dependency 'SwiftyJSON'
end
```
Notice I did not specify a version on any of those dependencies, that is because I am going to specify branches in my Podfile for the example project that is generated by `pod lib create`. That Podfile looks like this:
```
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Tablelist_Example', :exclusive => true do
  pod "Tablelist", :path => "../"
  
  pod 'Alamofire', '~> 2.0.0'
  pod 'KeychainAccess', :git => 'https://github.com/kishikawakatsumi/KeychainAccess.git', :branch => 'swift-2.0'
  pod 'ObjectMapper', '~> 0.16'
  pod 'Realm', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'swift-2.0'
  pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'swift-2.0'
  pod 'Starscream', :git => 'https://github.com/daltoniam/Starscream.git', :branch => 'Swift-2.0'
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git', :branch => 'xcode7'
end

target 'Tablelist_Tests', :exclusive => true do
  pod "Tablelist", :path => "../"
  
  pod 'Alamofire', '~> 2.0.0'
  pod 'KeychainAccess', :git => 'https://github.com/kishikawakatsumi/KeychainAccess.git', :branch => 'swift-2.0'
  pod 'ObjectMapper', '~> 0.16'
  pod 'Realm', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'swift-2.0'
  pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'swift-2.0'
  pod 'Starscream', :git => 'https://github.com/daltoniam/Starscream.git', :branch => 'Swift-2.0'
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git', :branch => 'xcode7'
  
  pod 'Quick', '~> 0.6.0'
  pod 'Nimble', '2.0.0-rc.3'
end
```
Now when I run `pod update` Cocoapods will grab the versions specified in my Podfile. My unit tests even work correctly. I can import the `Tablelist` module in my tests and access everything as expected.

**Comment by AnthonyMDev** [comment]
+1 I think its now an appropriate time to release a new version with Swift 2.0 support instead of needing to use the `branch:` tag.

Since the Xcode 7 GM seed was released, and we can now upload applications for iOS9, can we get an official release of this pod for Swift 2.0 please?

Thank you!

**Comment by evermeer** [comment]
@andrewBarba the fact that i cannot release my pod was the point. 'pod lib lint' will fail.

**Comment by AnthonyMDev** [comment]
@evermeer Yeah, I am now unable to release my pod as well because it has a dependency on this.

@kishikawakatsumi Can we expect this today? Otherwise I'm going to have to fork the project and create a whole new pod of my own. I'd really rather not do that.

**Comment by kishikawakatsumi** [comment]
@AnthonyMDev I might not have enough time sorry, I would like to release though... :cry:

**Comment by AnthonyMDev** [comment]
I mad a PR for this #108 today, so it should take long. If you don't have time, I'd be happy to do it for you, but you'd need to make me a contributor on this repository and a "owner" on the Cocoapod.

If you are willing to do that, it's really easy. Just `pod trunk add-owner AnthonyMDev@gmail.com` and make me an admin on the repo so I can do the edits to the pod spec.

I totally understand being too busy, everyone goes through those times, but you have 865 stars, and according to Cocoapods, 197 people using this pod in applications that can't be updated to use iOS9 currently, so this is pretty necessary.

Thanks for making such a helpful library @kishikawakatsumi . Let me know what you think.

**Comment by kishikawakatsumi** [comment]
I'm working on it.

**Comment by kishikawakatsumi** [comment]
I've release KeychainAccess 2.0.0 with Swift 2.0 support.  Thanks for your patience!! :bow:
