### ISSUE TITLE
keychain value not saved after I kill the app

### ISSUE THREAD

**Issue by fabdarice** [kishikawakatsumi/KeychainAccess#106]
Everytime I killed the app, my keychain's value are empty/nil.
I'm storing the value like this :
var keychain = Keychain(service: "myapp.app.service")
keychain["login"] = login
keychain["auth_token"] = auth_token

Then in my appDelegate didFinishLaunchingWithOptions, I do this var 

var keychain = Keychain(service: "myapp.app.service")
let login = keychain["login"]
let auth_token = keychain["auth_token"]

println(login)
println(keychain)

And after I kill the app and open it again, both my login and keychain are NIL. Anyone has any idea why my Keychains value are nil even though I never delete them? (I've tried both solution KeychainWrapper and KeychainAccess, both same behavior).

**Comment by fabdarice** [comment]
I don't know how but it seems to be working now..

**Comment by codwam** [comment]
Ihave the save problem that is run the simulator again has the before keychain?
@kishikawakatsumi

**Comment by iOSUser110** [comment]
I am still facing the same issue on device. Please anyone can help me out to solve this ? 
Keychain not string the values
