### ISSUE TITLE
Getting current warning on swift 2.0

### ISSUE THREAD

**Issue by allaire** [kishikawakatsumi/KeychainAccess#111]
`/Users/allaire/Dropbox/Projects/agendrix/ios/Pods/KeychainAccess/Lib/KeychainAccess/Keychain.swift:289:19: Unnecessary check for 'iOS'; minimum deployment target ensures guard will always be true`

```
var query = options.query()

query[kSecAttrAccount as String] = key
#if os(iOS)
if #available(iOS 9.0, *) {
    query[kSecUseAuthenticationUI as String] = kCFBooleanFalse
} else if #available(iOS 8.0, *) {
    query[kSecUseNoAuthenticationUI as String] = kCFBooleanTrue
}
#endif
```

**Comment by kishikawakatsumi** [comment]
This is for the iOS 7 users that they use this library to add the source code to their project directly.

**Comment by allaire** [comment]
Anyway to mute the warning then?

Thanks!

**Comment by allaire** [comment]
Also I think it would be nice to cut a release for swift-2.0 as it's now officialy out of beta and released!

**Comment by kishikawakatsumi** [comment]
If you are using CocoaPods for installing, how about using `inhibit_all_warnings!` ?

https://guides.cocoapods.org/syntax/podfile.html

**Comment by allaire** [comment]
@kishikawakatsumi Yeah I already have this flag set, maybe there's a bug with it using latest Xcode, because I still get the warnings!

**Comment by jwatson** [comment]
I'm also seeing this issue. Cocoapods 0.39.0.rc.1, iOS 9, Xcode 7.1. The `inhibit_all_warnings!` flag is present, but not helping.

**Comment by kishikawakatsumi** [comment]
OK, I'm going to drop iOS 7 support in the version after next version (2.2.0?)

**Comment by kishikawakatsumi** [comment]
https://github.com/kishikawakatsumi/KeychainAccess/issues/128
