### ISSUE TITLE
Merge swift 2.0 to master

### ISSUE THREAD

**Issue by allaire** [kishikawakatsumi/KeychainAccess#114]
I think it would good to cut an official release for swift 2.0 as it's now officially released.

Thanks!

**Comment by kishikawakatsumi** [comment]
Sorry, what do you mean? I'd released Swift 2.0 support version and merged swift-2.0 branch to master already.

**Comment by allaire** [comment]
@kishikawakatsumi I missed this! Sorry :beers:
