### ISSUE TITLE
merge Swift 2.0 branch

### ISSUE THREAD

**Issue by abunur** [kishikawakatsumi/KeychainAccess#116]
Swift 2.0 is now official / released with Xcode 7.  This should be merged to Master and Swift 2.0 branch deleted.  Additionally you might want to start a Swift 2.1 branch...

**Comment by kishikawakatsumi** [comment]
Swift 2.0 branch has been merged already. Swift 2.1 does not break our code anything, I guess. So we don't have anything to do, right?

**Comment by abunur** [comment]
ah OK I guess I was confused by the 2.0 branch still being around.  Delete it mayhap?  I will change my Podfile to use the main branch now.

thanks

**Comment by kishikawakatsumi** [comment]
Oh, I might forget to press "Delete branch" button. Thanks!

**Comment by kishikawakatsumi** [comment]
Uh, this PR https://github.com/kishikawakatsumi/KeychainAccess/pull/115 against `swift-2.0` branch. So I cannot delete `swift-2.0` branch until that PR is closed or merged.

**Comment by mspasov** [comment]
Sorry, closing #115. Should I reopen it against the integration branch?
