### ISSUE TITLE
Drop iOS 7 support

### ISSUE THREAD

**Issue by kishikawakatsumi** [kishikawakatsumi/KeychainAccess#128]
- [x] https://github.com/kishikawakatsumi/KeychainAccess/pull/126

**Comment by allaire** [comment]
@kishikawakatsumi Still getting `KeychainAccess/Keychain.swift:289:19: Unnecessary check for 'iOS'; minimum deployment target ensures guard will always be true`

**Comment by tobiasfeistmantl** [comment]
+1

**Comment by kishikawakatsumi** [comment]
https://github.com/kishikawakatsumi/KeychainAccess/issues/111
