### ISSUE TITLE
Question: Which Xcode version was used to compile the release binaries

### ISSUE THREAD

**Issue by mattijsf** [kishikawakatsumi/KeychainAccess#149]
Hi

I was wondering, which Xcode version was used to compile the pre-built binaries from https://github.com/kishikawakatsumi/KeychainAccess/releases? (2.2.0 specifically).

I'm asking because a specific (and weird) issue I experienced using Carthage to embed KeychainAccess in my project. More details here: https://github.com/Carthage/Carthage/issues/832

Could it be that they were created using an older version dan Xcode 7.0.1 (maybe one of the beta builds?)

**Comment by kishikawakatsumi** [comment]
2.2.0 and 2.1.0 are built with Xcode 7.0.1.

**Comment by mattijsf** [comment]
Thanks! Are those binaries build with Carthage itself? Sorry for all the questions but I'm trying to pinpoint an issue that I'm having with this Framework and the pre-built ones specifically.

**Comment by kishikawakatsumi** [comment]
Yes. Those binaries are built with Carthage command: https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file

```
carthage build --no-skip-current
carthage archive KeychainAccess
```
