### ISSUE TITLE
Set keychain key on iOS, access on Apple Watch (watchOS 2)?

### ISSUE THREAD

**Issue by acegreen** [kishikawakatsumi/KeychainAccess#151]
Is it possible to set a keychain key on iOS and get it on Apple Watch? would iCloud keychain need to be set in the settings.

**Comment by acegreen** [comment]
Looking through your Readme i found this:

let keychain = Keychain(service: "com.example.github-token")

do {
    try keychain
        .synchronizable(true)
        .set("01234567-89ab-cdef-0123-456789abcdef", key: "kishikawakatsumi")
} catch let error {
    print("error: \(error)")
}

What is service: 

All I want to do is set a key on iOS and retrieve it on Apple Watch.

**Comment by acegreen** [comment]
Also whats the difference between:


1. let token = keychain["kishikawakatsumi"]
2. let token = keychain[string: "kishikawakatsumi"]

3. let token = try? keychain.get("kishikawakatsumi")
4. let token = try? keychain.getString("kishikawakatsumi")

**Comment by kishikawakatsumi** [comment]
1 and 2 are same, just syntax sugar. 3 and 4 also same.
1, 2 and 3, 4 almost same other than `try?`. Return value of 3, 4 is String?? since you use `try?`. I don't recommend.

**Comment by acegreen** [comment]
Well my key is a string and value back is a string. but I'm not sure if its nil. Which method do I use. I tried 

        keychainRemoveAdsString  = try? keychain.get(removeAdsKey)

but its forcing me to wrap it like this:
        keychainRemoveAdsString  = try? keychain.get(removeAdsKey)!

then it crashes because key is empty.

**Comment by kishikawakatsumi** [comment]
```
if let keychainRemoveAdsString  = keychain[removeAdsKey] {

}
```

**Comment by acegreen** [comment]
Can’t do that I need my variable elsewhere in the code.

**Comment by kishikawakatsumi** [comment]
What do you mean? I cannot understand what you want to do.
Or you can use `guard` syntax.

```
guard let keychainRemoveAdsString = keychain[removeAdsKey] else {
    return
}

print(keychainRemoveAdsString)
```

**Comment by acegreen** [comment]
I don't want to define my variable at that point. I'm defining keychainRemoveAdsString on a class scale. So at that point I want to SET my variable and its ok if its nil but your try? causes a crash

**Comment by acegreen** [comment]
Ah funny that just doing keychainRemoveAdsString  = keychain[removeAdsKey] works without crash

**Comment by acegreen** [comment]
I don't think this issue is closed. We got side-tracked by other issues but I still can NOT set a key on iOS (iPhone) and retrieve it on Apple Watch. Can we detail the exact steps required?

Here is my snippet:

On iOS:
let keychain = Keychain(service: "AG.Chronic")
        // Set KeyChain Value
        do {
            try keychain
                .accessibility(.Always)
                .synchronizable(true)
                .set(proVersionKeyValue, key: proVersionKey)
        } catch let error {
            print("error: (error)")
        }

on watchOS:
let keychain = Keychain(service: "AG.Chronic")
keychainProVersionString = keychain[proVersionKey]

not sure if its not working because of simulator not having iCloud keychain functionality or I'm missing something. Do we need keychain sharing capability to be on with WatchOS 2?

**Comment by norio-nomura** [comment]
Apple wrote **"No iCloud Keychain"** in the Presentation Slides of ["WatchKit In-Depth, Part 2 - WWDC 2015 - Session 208 - watchOS"](https://developer.apple.com/videos/play/wwdc2015-208/).

**Comment by acegreen** [comment]
Ah this is so frustrating. So how does one successful recognize in-app purchases on Apple Watch. Currently I'm saving a key to keychain and on iOS 9 using updateApplicationContext to tell Apple Watch to save the same key on its keychain. This doesn't work for iOS 8, any suggestions?

**Comment by norio-nomura** [comment]
@acegreen Using watchOS 2 w/ iOS 8 is not supported by Apple.
Latest [Apple's document](https://support.apple.com/en-us/HT204505) that updated after release of watchOS 2 says:
> To use your Apple Watch, you need to pair it with an iPhone 5 or later running iOS 9 or later. 

It needs WatchKit 1 app to supporting Apple Watch on iOS 8.

**Comment by acegreen** [comment]
Oh that changes things. So technically my app updates with the new watch kit structure are then only available to users on WatchOS2 and therefore iOS9?

Thats GREAT news!!!

Thanks for the heads up

**Comment by acegreen** [comment]
iCloud keychain seems to be supported by watchOS now, does that mean this framework will work without having to transfer the info through watch connectivity and restore it on the watch side?

**Comment by gabehoffman** [comment]
I was attempting to do the same thing. However the part that needs to work is the iCloud Synchronizing for it move the data like we are wanting. 

According to the [current Apple Docs](https://developer.apple.com/library/archive/documentation/General/Conceptual/WatchKitProgrammingGuide/iOSSupport.html#//apple_ref/doc/uid/TP40014969-CH21-SW1), in the notes under the **Storing Data Securely in the Keychain**

>**NOTE**
>
>The kSecAttrSynchronizable key is **not** available in watchOS.

Without that, the WatchOS can't get the keychain data you've stored over on the iOS side. 

So I don't believe that's possible at this time.
