### ISSUE TITLE
Archiving issue 

### ISSUE THREAD

**Issue by acegreen** [kishikawakatsumi/KeychainAccess#153]
I ended up copying the project manually to get rid of the module issues. That all worked until I tried archiving the project and got the following error:

<img width="1375" alt="screen shot 2015-10-20 at 11 41 28 am" src="https://cloud.githubusercontent.com/assets/10794609/10612643/ab80004c-771f-11e5-9d6e-ad97cdb0e022.png">

please advice

**Comment by kishikawakatsumi** [comment]
Archiving is a pain to troubleshoot remotely. Can you send reprodicible sample project?

**Comment by acegreen** [comment]
I can’t! this is a production project and is pretty complex.

Can we Skype? id: aelalfy1989

**Comment by kishikawakatsumi** [comment]
I don't say to send production code. Just sample project. If it does not reproduse on other projects, you can resolve yourself investigating what is different.

**Comment by acegreen** [comment]
I’m unfortunately in a rush to push out an update as Apple is causing some trouble.

I would really appreciate it if I can show you the message on Skype.

**Comment by acegreen** [comment]
For future reference. The easiest way to import this library is to just copy the "Keychain.swift" file into the appropriate target. Spent a whole day trying the 3 options mentioned and they don't work, especially if you need this library for two targets.
