### ISSUE TITLE
Swift 2.1 build and archive

### ISSUE THREAD

**Issue by kylejm** [kishikawakatsumi/KeychainAccess#154]
Please could you make a new release with an archive attached build from Xcode 7.1 + Swift 2.1? The current release and archive don't work with Xcode 7.1 and Swift 2.1.

![screen shot 2015-10-22 at 15 04 24](https://cloud.githubusercontent.com/assets/3501212/10667241/34820aac-78ce-11e5-8e5b-9d5397541616.png)

Thanks! :smile:

**Comment by sxua** [comment]
Same thing here

**Comment by kishikawakatsumi** [comment]
You can build from source or setup via CocoaPods/Carthage until I will release fixed version.

**Comment by kylejm** [comment]
Did that before making the issue to fix in the interim. Sorry, should have mentioned it as a note in my description :sweat_smile:.

**Comment by sxua** [comment]
In my case, I setup it via Carthage, but .swiftmodules files are still from October 12, not sure who is in charge of this: Carthage itself or KeychainAccess :smile:

**Comment by kishikawakatsumi** [comment]
@sxua Because I provide pre-built framework. You can ignore that and force build to use `carthage update --no-use-binaries`

**Comment by kishikawakatsumi** [comment]
I've released v2.2.1, built with Xcode 7.1 and tvOS support! https://github.com/kishikawakatsumi/KeychainAccess/releases/tag/v2.2.1
