### ISSUE TITLE
Subclassing

### ISSUE THREAD

**Issue by thepelican** [kishikawakatsumi/KeychainAccess#174]
Hi All,

Im not sure if im doing this correctly, but im trying to subclass KeychainAccess.. 

The problem is that I cannot override any constructor cause the only designated is private and I cant call convenience constructors from the subclass..
My final goal is to create a singleton with Keychain:

  static let sharedInstance = KeychainManager() 

where.. class KeychainManager : Keychain 

Can anyone give me hand to understand?

Thanks

**Comment by kishikawakatsumi** [comment]
@thepelican I don't think subclassing is a good way for managing as a singleton. Maybe it is much easier that you use composition pattern? KeychainManager is a singleton that has a Keychain instance. Like following:

```swift
class KeychainManager {
    static let sharedInstance = KeychainManager()
    let keychain = Keychain(service: "...", accessGroup: "...")
}
```

**Comment by thepelican** [comment]
Thanks for the response.
Composition is what Im using right now, but im not satisfied with that.
I want my MYkeychain to be a KeychainAccess instance, So i can expose keychain interface plus other mykeychain ones.
 Do you have any reference on why inheriting form a singleton its a bad idea?

**Comment by kishikawakatsumi** [comment]
Generally, it is not possible to force the singleton pattern in subclassing. If you implement KeychainManager as singleton by subclassing, we can create Keychain instance anywhere. 

And also, I don't think it is intended to be used as a singleton. KeychainAccess provides fluent interfaces for configuration. A new instance is created for each method chain. It does not match well with the singleton pattern, I think.

**Comment by kishikawakatsumi** [comment]
Does it answer your question? I'm going to close this issue. Feel free to reopen this issue if you have any further questions.
