### ISSUE TITLE
Keychain value getting cleared if force closing app multiple time.

### ISSUE THREAD

**Issue by ashishfission** [kishikawakatsumi/KeychainAccess#194]
.Download build from test flight
.Login or store something in keychain
.Force close app multiple time
After 4-5 force close , keychain got cleared

**Comment by valeIT** [comment]
Still present?

**Comment by izikl** [comment]
Tried to repro on my device. I have terminated the app and reopened it for 10 times, with no repro (iPhone 6, iOS 9.2.1). 
Are you still seeing it?

**Comment by valeIT** [comment]
I've tried too since than and can't repro either (iPhone 5S, 9.2)

**Comment by MingLoan** [comment]
Did it solve?
