### ISSUE TITLE
Returning just key-value pairs as dictionary.

### ISSUE THREAD

**Issue by RyanKim01** [kishikawakatsumi/KeychainAccess#195]
When I'm returning all values, I noticed there are only two methods: allItems and allKeys.
Is there a way to return just key value pairs in one dictionary??

For example,  [ "last_name" : "value1", "first_name" : "value2" ].

Thank you!

**Comment by kishikawakatsumi** [comment]
No, you can use `allItems()`, then transform to the simple dictionary, instead.
