### ISSUE TITLE
is this library compatible with ObjC

### ISSUE THREAD

**Issue by farshidce** [kishikawakatsumi/KeychainAccess#196]
i was not able to import this library to an Objc project successfully.
i was reading through the minimum requirement for such compatibility and i noticed that the Swift classes do not carry @objc keyword with them so is this intentional or is it okay to contribute a patch for making the library Objc portable ?

**Comment by LinkedHK** [comment]
There  is already the objective c library(same maintainer )
https://github.com/kishikawakatsumi/UICKeyChainStore

**Comment by kishikawakatsumi** [comment]
@farshidce @LinkedHK is right. You can use https://github.com/kishikawakatsumi/UICKeyChainStore
