### ISSUE TITLE
RequestSharedWebCredential always returning empty array

### ISSUE THREAD

**Issue by ecristerna** [kishikawakatsumi/KeychainAccess#197]
`if` statement at line 873 always going false and returning credentials as empty array at line 889

**Comment by nickskull** [comment]
I am having the same issue. It displays the native popup, where user gets to choose an account, but after pressing ok I only get an empty array in the completion.

**Comment by nickskull** [comment]
Figured out a fix for the issue referenced above. Swift is not happy with casting an optional CFArray into a native one unfortunately. It might be a good idea to also write a bug report on the Swift bug tracker.

**Comment by ecristerna** [comment]
yes, it worked with your changes. thanks @nickskull
