### ISSUE TITLE
Documentation is incorrect

### ISSUE THREAD

**Issue by sovata8** [kishikawakatsumi/KeychainAccess#207]
Documentation mentions things such as:

`    try keychain.set("01234567-89ab-cdef-0123-456789abcdef", key: "kishikawakatsumi")`

Two issues here:
There is no such function. There is however a function called `set` `forKey`.

Secondly, this method does not actually throw any errors, so writing the above will result in a Swift warning.

So I am not sure how to even handle errors.

Documentation needs updating.

**Comment by kishikawakatsumi** [comment]
@sovata8 The documentation is correct.
The `set(_:, key:) throws` method is here: https://github.com/kishikawakatsumi/KeychainAccess/blob/master/Lib/KeychainAccess/Keychain.swift#L537

The method throws errors if it gets unexpected error from Keychain API, something like wrong certificate.

You seems other instace was stored in the `keychain` variable?
