### ISSUE TITLE
Target for iOS?

### ISSUE THREAD

**Issue by marbetschar** [kishikawakatsumi/KeychainAccess#208]
It would be nice to have a target inside the KeychainAccess project specifically for iOS.

As I can't use Cocoapods due to embedded frameworks are not supported I've included your KeychainAccess as git submodule into my iOS project and checked out the tag 2.3.5

Unfortunately I receive a `an unexpected Mach- O header code` after archiving when trying to upload to iTunes Connect.

This is due to the fact the KeychainAccess library is built for OS X by default (Base SDK is set to OS X).
Please add a second framework target, so this can be embedded in iOS projects without modifying your code / settings.

**Comment by kishikawakatsumi** [comment]
@marbetschar I don't think it is needed. This project includes all target platforms (iOS, macOS, wachOS and tvOS). I confirmed it could be embed/archived successfully using submodule. 

Can you show the reproducible project?

**Comment by marbetschar** [comment]
@kishikawakatsumi unfortunately I can't provide you a reproducible project - since I can't exactly remember what the issue was. Due to the fact I had several issues with Cocoapods during the last year, I've decided to move using Carthage. And since then everything works perfectly.

So feel free to close the issue - as per your description it sounds more like a error on my end instead of your library.

**Comment by falcon03** [comment]
Not having a specific target for iOS makes "My mac" appear in the valid destinations for building a project. This is annoying and I'm not sure wether it is hiding more complex issues, e.g. with iTunes Connect validation.
