### ISSUE TITLE
License not mentioned in Keychain.swift

### ISSUE THREAD

**Issue by meh-uk** [kishikawakatsumi/KeychainAccess#210]
Hey

This is a tedious t crossing issue, but I noticed that the MIT licence the project is licensed under isn't reflected in the source file and it appears that the source as a whole is all rights reserved.

**Comment by kishikawakatsumi** [comment]
Fixed by https://github.com/kishikawakatsumi/KeychainAccess/pull/225 Is it what you mean? @meh-uk

**Comment by meh-uk** [comment]
Yes thanks :)
