### ISSUE TITLE
Removing all keychain items when keychain is empty

### ISSUE THREAD

**Issue by zilions** [kishikawakatsumi/KeychainAccess#211]
I am trying to remove all keychain items from my app. Although, the code fails when the keychain is already empty.

Tried both `keychain.remove()` by looping over all keys, and also tried `keychain.removeAll()`, yet both failed with the same error.

Please see the StackOverflow question I posted that could not be solved.

http://stackoverflow.com/questions/36993530/using-keychainaccess-to-remove-all-items

**Comment by kishikawakatsumi** [comment]
Continue to discuss in StackOverflow http://stackoverflow.com/questions/36993530/using-keychainaccess-to-remove-all-items
