### ISSUE TITLE
OSX Dev ID 

### ISSUE THREAD

**Issue by MattTimmons** [kishikawakatsumi/KeychainAccess#212]
I am needing to store user/pass info in OS X keychain, but not with an AppStore App. I am able to use DeveloperID for this library ? I am not able to use keychain sharing as that is disallowed for non MAS apps.

**Comment by kishikawakatsumi** [comment]
@MattTimmons You should use your developer ID to build this framework. Xcode, CocoaPods and Carthage support signing your own developer ID.
