### ISSUE TITLE
keychain["value"] returns nested Optionals?

### ISSUE THREAD

**Issue by arashdoescode** [kishikawakatsumi/KeychainAccess#214]
How do solve this problem? the result would

Optional("Optional(John)")

tried this solution but doesnt work

 ```
   if let firstName = keychain["first_name"] {
            print(" My name is \(firstName)")
        }

```

as well as

```
if let firstName = keychain["first_name"]! {
            print(" My name is \(firstName)")
        }
```

received an error = 

> Initializer for conditional binding must have Optional type, not ’String’

**Comment by kishikawakatsumi** [comment]
@arashdoescode The subscripting returns optional value, not nested optional. I cannot reproduce it. Can you share the reproducible project?

**Comment by arashdoescode** [comment]
Kishi thank you for fast reply, I made a mistake on my side actually, Have solved it.
