### ISSUE TITLE
Swift 2.3

### ISSUE THREAD

**Issue by KingOfBrian** [kishikawakatsumi/KeychainAccess#217]
Swift 2.3 changed the rawValue type of `SecAccessControlCreateFlags` to `CFOptionFlags` from `CFIndex` -- aka to `UInt` from `Int`.

**Comment by BilalReffas** [comment]
What about Swift 3? There is currently no branch for it

**Comment by MKGitHub** [comment]
Any news for Swift 3? Hello? Wake up!!

**Comment by h3smith** [comment]
Anyone is free to branch and upgrade to Swift 3 themselves. Seeing as it is a few months out from being RTM and changes will be in flux, there isn't much reason to jump at it yet.

**Comment by kishikawakatsumi** [comment]
Swift 2.3 branch is up https://github.com/kishikawakatsumi/KeychainAccess/issues/217
