### ISSUE TITLE
Code won't compile with iOS 10 Beta 2 SDK

### ISSUE THREAD

**Issue by lvandal** [kishikawakatsumi/KeychainAccess#233]
There are some syntax changes in Swift 3 that Beta 2 introduced. For example, `bundle()` has been replaced by `bundle`.

**Comment by kishikawakatsumi** [comment]
@lvandal Thanks! Fixed at https://github.com/kishikawakatsumi/KeychainAccess/pull/221/commits/ff182ed621748d80e79dc86516c332de95dbaf7f

**Comment by lvandal** [comment]
Thanks!
