### ISSUE TITLE
LAError is not thrown

### ISSUE THREAD

**Issue by cikpis** [kishikawakatsumi/KeychainAccess#234]
If we use Touch ID and an error is thrown we receive an ErrorType instead of LAError.
Would be nice if we can handle by ourself it.

Carmelo

**Comment by kishikawakatsumi** [comment]
@cikpis You are mixing Security.framework and LocalAuthentication.framework. Keychain with touch ID integration doesn't use LocalAuthentication.framework. It is part of Security.framework. Security.framework never throw LAError.

**Comment by cikpis** [comment]
I wrote that because as far as I know you can display the Touch ID session only using LocalAuthentication.framework. Just for my curiosity, how are you displaying the Touch ID without that framework?

**Comment by kishikawakatsumi** [comment]
@cikpis Yes.To protect keychain value with touch ID, use `SecAccessControl` object to save values. 

```
struct SecAccessControlCreateFlags : OptionSetType {
    init(rawValue rawValue: CFIndex)
    static var UserPresence: SecAccessControlCreateFlags { get }
    static var TouchIDAny: SecAccessControlCreateFlags { get }
    static var TouchIDCurrentSet: SecAccessControlCreateFlags { get }
    static var DevicePasscode: SecAccessControlCreateFlags { get }
    static var Or: SecAccessControlCreateFlags { get }
    static var And: SecAccessControlCreateFlags { get }
    static var PrivateKeyUsage: SecAccessControlCreateFlags { get }
    static var ApplicationPassword: SecAccessControlCreateFlags { get }
}
```

It's not related with LocalAuthentication. Instead Security.framework returns some error like `errSecAuthFailed`, `errSecInteractionNotAllowed`, etc. when touch ID auth failed.

**Comment by kishikawakatsumi** [comment]
I'm assuming this is an answer for you? Closing this issue now. If you have any more questions pleae reopen the issue.
