### ISSUE TITLE
Fails to compile with Carthage and Xcode 8 Beta 3

### ISSUE THREAD

**Issue by lvandal** [kishikawakatsumi/KeychainAccess#248]
`--- xcodebuild: WARNING: Unable to open project file '/Users/lucvandal/Repositories/Screens 4/screens-4-ios/Vendor/Carthage/Checkouts/KeychainAccess/Examples/Playground-iOS.playground' in workspace '/Users/lucvandal/Repositories/Screens 4/screens-4-ios/Vendor/Carthage/Checkouts/KeychainAccess/KeychainAccess.xcworkspace'.
** CLEAN FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/lucvandal/Repositories/Screens 4/screens-4-ios/Vendor/Carthage/Checkouts/KeychainAccess/KeychainAccess.xcworkspace -scheme KeychainAccess -configuration Release -sdk watchos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
--- xcodebuild: WARNING: Unable to open project file '/Users/lucvandal/Repositories/Screens 4/screens-4-ios/Vendor/Carthage/Checkouts/KeychainAccess/Examples/Playground-iOS.playground' in workspace '/Users/lucvandal/Repositories/Screens 4/screens-4-ios/Vendor/Carthage/Checkouts/KeychainAccess/KeychainAccess.xcworkspace'.
** CLEAN FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)`

**Comment by kishikawakatsumi** [comment]
It might be fixed by https://github.com/kishikawakatsumi/KeychainAccess/pull/249

**Comment by kishikawakatsumi** [comment]
I think now `swift-3.0` branch can be built with Xcode 8 beta3. If you have any problems, please reopen or file another issue.

**Comment by mahmoud-cliqz** [comment]
I updated to Carthage 0.18 and still have same problem with `Alamofire`

    *** Building scheme "Alamofire watchOS" in Alamofire.xcworkspace
    --- xcodebuild: WARNING: Unable to open project file '/Users/mahmoud/firefox/Carthage/Checkouts/Alamofire/Alamofire.playground' in workspace '/Users/mahmoud/firefox/Carthage/Checkouts/Alamofire/Alamofire.xcworkspace'.
    ** CLEAN FAILED **
	The following build commands failed:
		Check dependencies
	(1 failure)
	** BUILD FAILED **
	The following build commands failed:
		Check dependencies
	(1 failure)
	A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/mahmoud/firefox/Carthage/Checkouts/Alamofire/Alamofire.xcworkspace -scheme "Alamofire watchOS" -configuration Release -sdk watchos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
	--- xcodebuild: WARNING: Unable to open project file '/Users/mahmoud/firefox/Carthage/Checkouts/Alamofire/Alamofire.playground' in workspace '/Users/mahmoud/firefox/Carthage/Checkouts/Alamofire/Alamofire.xcworkspace'.
	** CLEAN FAILED **
	The following build commands failed:
		Check dependencies
	(1 failure)
	** BUILD FAILED **
	The following build commands failed:
		Check dependencies
	(1 failure)
