### ISSUE TITLE
OSStatus error:[-50] with Xcode 8 beta 6

### ISSUE THREAD

**Issue by thebluepotato** [kishikawakatsumi/KeychainAccess#254]
Accessing the Keychain with the latest commit https://github.com/kishikawakatsumi/KeychainAccess/commit/fe19b69ec5d4698898c7807daba8eaf5a8dde335 produces following error `OSStatus error:[-50] One or more parameters passed to a function were not valid.` This is equivalent to `errSecParam`. `Keychain.get(_:)`, `Keychain.allKeys()` or `debugDescription` are all empty.
Is there an issue on my side or is it a bug?

**Comment by thebluepotato** [comment]
After a bit of testing I've discovered that the tests bundled with the swift-3 branch also output the same error so the bug is within the latest commit or within Xcode 8 beta 6.

**Comment by thebluepotato** [comment]
@kishikawakatsumi To help you pinpoint the issue, all `set*` tests fail and I think it's because `get(_:)` throws `errSecParam`, therefore making it impossible to assert whether `set()`has worked or not. That's my best guess, because my app uses existing Keychain entries (already set) and getting them fails. I haven't tested only setting then looking at the entry in the Keychain app in macOS.
I'd wager that the lack of implicit bridging in beta 6 has lead to one or more of the params to `secItemCopyMatching()` to be of the wrong type.

**Comment by kishikawakatsumi** [comment]
@thebluepotato Thanks for reporting!

This issue due to implicit conversion to CFType being gone. Now fixed https://github.com/kishikawakatsumi/KeychainAccess/pull/221
