### ISSUE TITLE
Fix deprecation warning for deployment targets higher than iOS 9

### ISSUE THREAD

**Issue by felixLam** [kishikawakatsumi/KeychainAccess#255]
Currently we get a deprecation warning when building with deployment target higher than iOS 9:
```
...KeychainAccess/Lib/KeychainAccess/Keychain.swift:1114:44: 'kSecUseNoAuthenticationUI' was deprecated in iOS 9.0: Use a kSecUseAuthenticationUI instead.
```

This is correctly checked at the call-site,  but the implementation here needs to go somewhere else. My suggestion would be to inline `String(kSecUseNoAuthenticationUI)` in line 568.

**Comment by felixLam** [comment]
Alternatively we can change the declaration of `UseNoAuthenticationUI`. Given that this is private the missing deprecation warning should not be an issue:

```swift
#if os(iOS)
    private let UseNoAuthenticationUI: String = {
        if #available(iOS 9.0, *) {
            assertionFailure("`UseNoAuthenticationUI` has been deprecated. Use `UseAuthenticationUI` instead.")
            return UseAuthenticationUI
        } else {
            return String(kSecUseNoAuthenticationUI)
        }
    }()
#endif
```

**Comment by kishikawakatsumi** [comment]
I don't think it is a problem. Because KeychainAccess is provided as deployment target 8.0. Also it seems that your solution doesn't suppress the warnings.

**Comment by felixLam** [comment]
HI @kishikawakatsumi the warning occur when including `Keychain.swift` directly in a project. This is currently necessary because we use it in an extension and Xcode+iTunes don't like bundled frameworks. We tested both of the above suggestions and these did silence the warning.

**Comment by kishikawakatsumi** [comment]
@felixLam I understand what's happened. But I cannot find a good way to resolve this on my side. Maybe it might be better that suppressing on your side. I'll close this issue due to nothing to do. If you have any better options, feel free to reopen and please let me know. Thanks for the reporting!
