### ISSUE TITLE
Framework signing

### ISSUE THREAD

**Issue by dylan** [kishikawakatsumi/KeychainAccess#261]
You don't need to sign the framework now as of iOS9/10 I believe. If you can remove your provisioning profile from the project in the swift3.0 branch?

Thanks! (Awesome project btw, very handy!)

**Comment by kishikawakatsumi** [comment]
@dylan The provisioning profile needs for tests. The way of unit tests was changed to using host application. The code signing is needed for building host application (also frameworks).

The unit tests with host application is useful than logic tests. Because it is more close to the actual use cases. Especially on OS X.

Is my understanding correct?

**Comment by dylan** [comment]
This is a good question. My issue is that I use Carthage to build the frameworks and link against them, this works. But I also need to include the project in my workspace to use with playgrounds, but when I build the project I have to go into KeychainAccesses target to deselect the provisioning profile.

**Comment by fantattitude** [comment]
I have the same problem @dylan has. I'm using the framework as a sub framework of my app's framework and must remove "Development Team" for it to accept building for iOS.

Here's what I must do to get it to compile on device :

```
diff --git a/Lib/KeychainAccess.xcodeproj/project.pbxproj b/Lib/KeychainAccess.xcodeproj/project.pbxproj
index f520e87..1f98c2c 100644
--- a/Lib/KeychainAccess.xcodeproj/project.pbxproj
+++ b/Lib/KeychainAccess.xcodeproj/project.pbxproj
@@ -272,7 +272,6 @@
                                TargetAttributes = {
                                        140F195B1A49D79400B0016A = {
                                                CreatedOnToolsVersion = 6.1.1;
-                                               DevelopmentTeam = 27AEDK3C9F;
                                        };
                                        140F19661A49D79500B0016A = {
                                                CreatedOnToolsVersion = 6.1.1;
@@ -402,6 +401,7 @@
                        isa = XCBuildConfiguration;
                        baseConfigurationReference = 148E44EB1BF9EEB3004FFEC1 /* KeychainAccess.xcconfig */;
                        buildSettings = {
+                               DEVELOPMENT_TEAM = "";
                        };
                        name = Debug;
                };
@@ -409,6 +409,7 @@
                        isa = XCBuildConfiguration;
                        baseConfigurationReference = 148E44EB1BF9EEB3004FFEC1 /* KeychainAccess.xcconfig */;
                        buildSettings = {
+                               DEVELOPMENT_TEAM = "";
                        };
                        name = Release;
                };
```

Do you really need to run your tests against a device requiring signing ?

**Comment by raven** [comment]
I'm in the same boat as @dylan and @fantattitude

**Comment by raven** [comment]
I've created a PR: https://github.com/kishikawakatsumi/KeychainAccess/pull/274

**Comment by muescha** [comment]
PR is merged - problems are gone?
