### ISSUE TITLE
dyld: Symbol not found: __TMps10Streamable

### ISSUE THREAD

**Issue by BalestraPatrick** [kishikawakatsumi/KeychainAccess#262]
I'm building an iOS Message extension and linking KeychainAccess to it with Carthage. It always worked fine but if I build my app with Xcode 8 GM it crashes on launch with the following error:
`dyld: Symbol not found: __TMps10Streamable`

Does this only happen with my specific configuration or is it reproducible with other configurations?

**Comment by AndrewSB** [comment]
FYI: I found this through Google, Im getting the same problem with github.com/thoughtbot/Argo

```
dyld: Symbol not found: __TMps10Streamable
  Referenced from: /Users/asb/Library/Developer/CoreSimulator/Devices/E13A36BE-50DE-4892-8811-B397655F1EC4/data/Containers/Bundle/Application/81E94CE2-DCCE-40BA-BD13-E5F8221B0F7B/wrytr.app/Frameworks/Argo.framework/Argo
  Expected in: /Users/asb/Library/Developer/CoreSimulator/Devices/E13A36BE-50DE-4892-8811-B397655F1EC4/data/Containers/Bundle/Application/81E94CE2-DCCE-40BA-BD13-E5F8221B0F7B/wrytr.app/Frameworks/libswiftCore.dylib
 in /Users/asb/Library/Developer/CoreSimulator/Devices/E13A36BE-50DE-4892-8811-B397655F1EC4/data/Containers/Bundle/Application/81E94CE2-DCCE-40BA-BD13-E5F8221B0F7B/wrytr.app/Frameworks/Argo.framework/Argo
```

**Comment by mz2** [comment]
Have you rebuilt your Carthage dependencies since moving to the GM? I had the same with a bunch of dependencies going from beta 6 to GM, took me a while to remember that libraries need to be matched with the Xcode version you are building your main binary with.
