### ISSUE TITLE
Swift 2.3 / 3 Support

### ISSUE THREAD

**Issue by twiedow** [kishikawakatsumi/KeychainAccess#263]
Hi,

I just like to know how your plans are about a Swift 2.3 / Swift 3 compatible version?

Thanks,

Tobi

**Comment by ashutosh-android** [comment]
Hi , 

I am trying to use your swift-3.0 branch but there are still issues. I am using Xcode 8 GMSeed and my podfile is like
pod 'KeychainAccess', git: 'git@github.com:kishikawakatsumi/KeychainAccess.git', branch: 'swift-3.0'

Event after using this, when I try to open my app it ask to convert this project to Swift 3.0, and it shows a diff for Keychain.swift file. Even if I merge suggested changes there is still error in project.

Please understand I am using this library from sometime and it's very critical for my project . Let me know if I am doing naything wrong, or there are any plans to fix this.

**Comment by twiedow** [comment]
I just checked out the 2.3 branch and tried the example. There is a strange behavior (which lets the example app crash) where the IBAction from the InputViewController is called cancelAction(sender: AnyObject) but in the storyboard it is listed as cancelActionWithSender:

This seems odd to me because actually Xcode or the Interface Builder should handle it like in Swift 2 and use the name cancelAction: in the storyboard.

Are you having this issue as well?

**Comment by twiedow** [comment]
Btw, when I open the workspace (Swift 2.3 or 3 branch) Xcode shows me a warning that the project settings are not up-to-date.

**Comment by kishikawakatsumi** [comment]
@twiedow Use `swift-2.3` or `swift-3.0` branch.

**Comment by kishikawakatsumi** [comment]
Update:
v2.4.x is for Swift 2.3, v3.x is for Swift 3
https://github.com/kishikawakatsumi/KeychainAccess#requirements
