### ISSUE TITLE
synchronizable(true) and accessGroup not iCloud Syncing

### ISSUE THREAD

**Issue by Sun3** [kishikawakatsumi/KeychainAccess#264]
I am trying to get the iCloud Syncing working with accessGroup but when I test on other devices the value does not come through.

```
let keychain = Keychain(service: "com.company.App", accessGroup: "group.com.company.App").synchronizable(true)
        let isEnabled = try! keychain.getString("isEnabled")
```

Any ideas?
Thanks

**Comment by Sun3** [comment]
Just checking on any progress on this issue. 

Thanks.

**Comment by rogomantik** [comment]
Same for me, I can't find the saved key anywhere in the mac keychain app (should be listed there as application passord-Pencil with three dots, right?)
I store and get a Bool value from an iOS app this way
 ```
private static let keyChain = Keychain(service: "serviceKeychainString").synchronizable(true)

class func set(mVal: Bool) -> Bool {
        do {
            try keyChain.set(NSKeyedArchiver.archivedData(withRootObject: NSNumber(value: mVal)), key: "theKey")
        } catch {
            return false
        }
        return true
    }
class func getValue() -> Bool {
        var mValue: Data?
        do {
            mValue = try keyChain.getData("theKey")
        } catch {
            return false
        }
        if mValue == nil {
            return false
        }
        let boolValue = (NSKeyedUnarchiver.unarchiveObject(with: mValue!) as! NSNumber).boolValue
        
        return boolValue
    }
```
I've enabled the keychain sharing in the project (not iCloud)
It works within the same app/appExtension, not tested different ios devices
I can set the value in the app and retrieve in the extension

**Comment by rogomantik** [comment]
Update
I fount that the Cababilities - Keychain Sharing - Keychain groups String
(the one you set) is different from the one declared in the entitlements
Example
I write    **group.key.my**
And i got in the entitlements
```
<key>keychain-access-groups</key>
	<array>
		<string>$(AppIdentifierPrefix)group.key.my</string>
	</array>

```

There is a $(AppIdentifierPrefix) more (is the developerGroup followed by a dot
Don't know if can be removed manually (for now i give a solution to add it programmatically to the keychain call

so the solution may be:
Set in all (all the apps / extension with the same Keychain group) info.plist the a value like

```
<key>KaychainGroup</key>
    <string>$(AppIdentifierPrefix)group.key.my</string>
```
 then use it this way
```
let keyChain = Keychain(service: Bundle.main.object(forInfoDictionaryKey: "KaychainGroup") as! String).synchronizable(true)
```
@Sun3 can you test with your devices?

**Comment by kkieffer** [comment]
I also had the same issue and just tried your solution now and it works.  I'm able to see the app password in MacOS keychain. Also, if you add a .label() when you create your Keychain it shows up with a friendly readable name, otherwise it shows up as  string $(AppIdentifierPrefix)group.key.my

Also doesn't appear you can remove $(AppIdentifierPrefix) from the entitlements file, it won't build without it.
