### ISSUE TITLE
Swift 3 and iOS 10

### ISSUE THREAD

**Issue by Sun3** [kishikawakatsumi/KeychainAccess#269]
As anyone able to compile with Swift 3 and iOS 10? Suggestions?

Thanks.

**Comment by Cyclic** [comment]
It also looks like the swift-2.3 branch was deleted, so I'm unable to compile with swift-2.3 either. Any suggestions for this too?

    pod 'KeychainAccess', :git => 'https://github.com/kishikawakatsumi/KeychainAccess.git', :branch => 'swift-2.3'

**Comment by kishikawakatsumi** [comment]
@Sun3 @Cyclic 

`swift-2.3` branch has been released as `v2.4.0`. `swift-3.0` branch also has been released as `v3.0.0`. Please see https://github.com/kishikawakatsumi/KeychainAccess/pull/268 


|            | OS                                     | Swift         |
|------------|----------------------------------------|---------------|
| **v1.1.x** | iOS 7+, OSX 10.9+                      | 1.1           |
| **v1.2.x** | iOS 7+, OSX 10.9+                      | 1.2           |
| **v2.0.x** | iOS 7+, OSX 10.9+, watchOS 2+          | 2.0           |
| **v2.1.x** | iOS 7+, OSX 10.9+, watchOS 2+          | 2.0           |
| **v2.2.x** | iOS 8+, OSX 10.9+, watchOS 2+, tvOS 9+ | 2.0, 2.1      |
| **v2.3.x** | iOS 8+, OSX 10.9+, watchOS 2+, tvOS 9+ | 2.0, 2.1, 2.2 |
| **v2.4.x** | iOS 8+, OSX 10.9+, watchOS 2+, tvOS 9+ | 2.2, 2.3      |
| **v3.x**   | iOS 8+, OSX 10.9+, watchOS 2+, tvOS 9+ | 3.0           |
