### ISSUE TITLE
Cannot call value of non-function type '[String : Any]'

### ISSUE THREAD

**Issue by adhiravishankar** [kishikawakatsumi/KeychainAccess#272]
var (attributes, error) = options.attributes(key: key, value: value)
 is returning the error in the title.

**Comment by adhiravishankar** [comment]
Also, this line:

            var (attributes, error) = options.attributes(key: nil, value: value)

**Comment by kishikawakatsumi** [comment]
@adhiravishankar Please try clean & rebuild. Then errors won't be resolved, could you please show me more details. What versions of library and Xcode did you use? I cannot reproduce that and all builds & tests are passed in any versions of this library.

**Comment by adhiravishankar** [comment]
ok, it seems to be fixed now.

**Comment by darthmarku** [comment]
Hi @kishikawakatsumi, I'm using KeychainAccess 3.0 on Xcode 8 and I'm getting these errors too. I've done cleans and rebuilds but the error persists.

**Comment by kishikawakatsumi** [comment]
@darthmarku How did you set up your project? Can you please share the project to me for investigating?

**Comment by darthmarku** [comment]
@kishikawakatsumi Sorry for the bother, but when I did a 
`pod 'KeychainAccess', :git => 'https://github.com/kishikawakatsumi/KeychainAccess'`
instead of simply
`pod 'KeychainAccess'`
the problem went away.

**Comment by kramsretep** [comment]
I just updated to the latest version (3.0.0), and I too am seeing this problem. The work-around mentioned above didn't help. I'm running XCode 8.0 (8A218a). The project is unfortunately too big to attach here. What can I provide instead?
