### ISSUE TITLE
Swift 3.0 error

### ISSUE THREAD

**Issue by walkline** [kishikawakatsumi/KeychainAccess#273]
I have next issue with xcode 8 and Swift 3.0:
![image](https://cloud.githubusercontent.com/assets/444158/18559675/fabd890c-7b80-11e6-9d7b-45b3a9f04fd6.png)
Can you help me fix that? 
I'm using 3.0.0 version of your pod.

**Comment by ogezue** [comment]
same here

**Comment by back2mach** [comment]
same here

**Comment by back2mach** [comment]
I check the definition. Using options.attributes(nil, value: value) works.

**Comment by kishikawakatsumi** [comment]
@walkline @back2mach No, first parameter label is needed from Swift 3. `options.attributes(key: nil, value: value)` is correct. Can you try clean & rebuild? Or please share repro project. `v3.0.0` can be built successfully in my env and [CI](https://travis-ci.org/kishikawakatsumi/KeychainAccess/builds/160059884).

**Comment by back2mach** [comment]
but your definition explicitly omits the first parameter label: 
Line 1192: func attributes(_ key: String?, value: Data) -> ([String: Any], Error?)

**Comment by kishikawakatsumi** [comment]
@back2mach No. https://github.com/kishikawakatsumi/KeychainAccess/blob/master/Lib/KeychainAccess/Keychain.swift#L1192
Maybe you are using something wrong versions of source.

**Comment by back2mach** [comment]
@kishikawakatsumi Oh, yes. You're right. Now it works fine. :) Thanks

**Comment by kishikawakatsumi** [comment]
No problem, glad to hear it. 
@walkline Could you please make sure updating latest version of code and clean & rebuild it?

**Comment by timsp8** [comment]
I think it is when you run your code through the Convert to Swift 3 in Xcode 8. It is prefixing with an underscore and this is the crux of the problem.

func attributes(_ key: String?, value: Data) -> ([String: Any], Error?) {

**Comment by walkline** [comment]
Yeah problem was solved with rerun $pod update.
Thanks!

**Comment by leizard** [comment]
When I change to version 3.0 for Swift 3 migration. My code not work anymore. Every keychain["keyvalue"] return nil. Did I miss something ?

**Comment by leizard** [comment]
Hi, 
I found out that keychain["keyvalue"] works when I run on device, but always return nil when I run on simulator. Don't know if it s related to Swift 3 migration. Could anybody help me on this ?
Thank you

**Comment by kishikawakatsumi** [comment]
@leizard Your issue might be resolved by https://github.com/kishikawakatsumi/KeychainAccess/issues/52#issuecomment-247019997

**Comment by leizard** [comment]
Thank you for your support @kishikawakatsumi. Definitely save my day.
