### ISSUE TITLE
KeychainAccess return sometimes empty value

### ISSUE THREAD

**Issue by BilalReffas** [kishikawakatsumi/KeychainAccess#277]
I have a Issue which I don't really understand sometimes the Keychain is empty without any reason. 
Look's like I have the same Issue like this [http://stackoverflow.com/questions/36285783/keychain-sometimes-returns-empty-value](url)

Other people with the same issue ?

I observed some other app's like Telegram or Slack where I was kick out sometimes maybe it's a issue from Keychain from Apple. I'm not really sure.. :/

**Comment by x4080** [comment]
Hello, in my case it will always empty if I'm running it from the actual device after installing it from Xcode, so the breakdowns :

- IOS 10 Simulator : works
- Device iOS 8 : works (32 bit)
- Device IOS 9.3.3 : works only if running from Xcode (64 bit)

Using Xcode 8, Mac OS Sierra, free developer certificate (6 days limit), using keychain sharing on

**Comment by IvoPintodaSilva** [comment]
Same thing happens to me. Sometimes I get an empty value from the Keychain. Did anyone find a reliable fix for this?

**Comment by Cyclic** [comment]
@IvoPintodaSilva I have this issue as well. Is it the security level that your keychain is set to? For example, I have seen this issue if the permission is only set to allow access after first unlock or after unlock. Please let me know if you found a solution.

**Comment by koshilife** [comment]
This issue might happen to our product.
I want to differentiate this empty problem and understand whether it is heppen to our product or not.

@kishikawakatsumi  @BilalReffas  @IvoPintodaSilva 
I have a question.
Does the empty value means KeychainAccess returns _**String**_ empty value?

**Comment by jarnoverreyt** [comment]
Does someone already have a solution? This also happens in my app.

**Comment by Cyclic** [comment]
First unlock is the one right after you boot and unlock. Any subsequent unlock is just an unlock. Usually apps that start right after phone boot (I forget the name of these, but it’s defines in the docs) require access before first unlock.

**Comment by iShavgula-TacTill** [comment]
Thanks for the explication.
In my case, the application does not require access before the first unlock, but still there have been some users who were getting empty values and they could not even update the existing value.

Scenario goes like this:
`- if value exists
 — return value
 - else
 — generate newValue
 — save newValue
 — retenu newValue
- endIf `

Those users where generating new values on every app opening (max 1 generation per opening) and after app re-install they all got their initial values.

**Comment by pouriaalmassi** [comment]
Was there ever any investigation or resolution to this issue?

**Comment by sahibhussain** [comment]
sometimes it takes time to decrypt your data after iOS 15 due to pre-warming of the app  as app is warmed even before any data access permission is provided. 

there is notification event to check the `UIApplication.protectedDataDidBecomeAvailableNotification`

here is my sample code

```
if UIApplication.shared.isProtectedDataAvailable {
            didDataAvailable()
        }else {
            NotificationCenter.default.addObserver(self, selector: #selector(didDataAvailable), name: UIApplication.protectedDataDidBecomeAvailableNotification, object: nil)
        }
```
this should solve your problem.
