### ISSUE TITLE
Cannot call value of non-function type '[String : Any]'

### ISSUE THREAD

**Issue by maheshmobile** [kishikawakatsumi/KeychainAccess#280]
I am getting Compile error "**Cannot call value of non-function type '[String : Any]'**" error on line number 593 & 618 in KeychainAcess.swift file.

**Comment by dfmuir** [comment]
I am also seeing this issue after installing with Cocoapods on Xcode 8.

**Comment by kishikawakatsumi** [comment]
Closing as duplicated to https://github.com/kishikawakatsumi/KeychainAccess/issues/273 and https://github.com/kishikawakatsumi/KeychainAccess/issues/272

**Comment by dis123** [comment]
Still getting this issue on Xcode Version 8.1 (8T61a). I try all the steps provided by you but still facing the same issue.

**Comment by Arvindcs** [comment]
how to slove that problem I am getting Compile error "Cannot call value of non-function type '[String : Any]'" error  in swift 5
