### ISSUE TITLE
Should i call something like synchronize like UserDefaults?

### ISSUE THREAD

**Issue by ivanruizscm** [kishikawakatsumi/KeychainAccess#286]
Sometimes seems the tokens are not saved or i can't read them?
This class its correct?

import KeychainAccess

class DataStorage {

```
    private static let keychain = Keychain(service: Identifiers.GCalendar)

    private struct Identifiers {
        static let GCalendar = "OAuthGoogleCalendar"
        static let token = "the_token_key1"
        static let secretToken = "the_secret_token_key1"
    }

    class func saveTokens(token: String, secretToken: String) {
        keychain[string: Identifiers.token] = token
        keychain[string: Identifiers.secretToken] = secretToken
    }

    @discardableResult
    class func getTokens() -> (token: String, secretToken: String) {
        return (keychain[Identifiers.token] ?? "", keychain[Identifiers.secretToken] ?? "")
    }

    class func existsToken() -> Bool {
        return keychain[Identifiers.token]  != nil
    }

    class func removeTokens() {
        do {
            try keychain.remove(Identifiers.token)
            try keychain.remove(Identifiers.secretToken)
        } catch let error {
            print("error removing tokens \(error.localizedDescription)")
        }
    }
```

}

**Comment by kishikawakatsumi** [comment]
@ivanruizscm `DataStorage` class seems fine. Could you show me more details?
How did you use this class?

**Comment by ivanruizscm** [comment]
@kishikawakatsumi when those values are stored? 
After calling DataStorage. saveTokens(token:"a", secretToken: "b") i can retreive them?
Sometimes seems not.

**Comment by cikpis** [comment]
Hi @kishikawakatsumi, I have the same problem.

```               
let tmpKeychain = Keychain(service: "test")
tmpKeychain["auth-token"] = token.accessToken
tmpKeychain["auth-refresh-token"] = token.refreshToken
tmpKeychain["auth-expires-in"] = token.expiresIn.description
tmpKeychain["auth-timestamp"] = NSDate().timeIntervalSince1970.description
```

Any clue why the keychain is always empty? Seems like the keys are not stored.

**Comment by ivanruizscm** [comment]
@cikpis not always! ;)

**Comment by cikpis** [comment]
@ivanruizscm for me is always :) Both on Swift 2.3 and 3.0

**Comment by cikpis** [comment]
Doing the try and catch I got this error:

```
let keychain = Keychain(service: "test")
    do {
         try keychain.set("01234567-89ab-cdef-0123-456789abcdef", key: "kishikawakatsumi")
    } catch let error {
        print(error)
    }
```
`
OSStatus error:[-34018] Internal error when a required entitlement isn't present, client has neither application-identifier nor keychain-access-groups entitlements.
Error Domain=com.kishikawakatsumi.KeychainAccess.error Code=-34018 "Internal error when a required entitlement isn't present, client has neither application-identifier nor keychain-access-groups entitlements." UserInfo={NSLocalizedDescription=Internal error when a required entitlement isn't present, client has neither application-identifier nor keychain-access-groups entitlements.}
`

**Comment by cikpis** [comment]
Fixed!

Just need to enable the Keychain Sharing on my target capabilities :wink:

**Comment by pgbear** [comment]
If you are using NSEncoding protocol, you need to look at the changes in Swift3 for decodeBool and decodeInteger instead of decodeObject. That fixed my issue
