### ISSUE TITLE
Swift 3 migration issue

### ISSUE THREAD

**Issue by solal** [kishikawakatsumi/KeychainAccess#287]
Hi Kishikawa,
I just updated to Swift 3 and I'm now getting an error from your framework (using `pod 'KeychainAccess', '~> 3.0.0'`) that says: _Cannot call value of non function type '[String: Any]'_

It happens twice when you're calling:
```swift
var (attributes, error) = options.attributes(key: nil, value: value)
if let error = error {
    print(error.localizedDescription)
    throw error
}
```

And:
```swift
var (attributes, error) = options.attributes(key: key, value: value)
if let error = error {
    print(error.localizedDescription)
    throw error
}
```

![screen shot 2016-10-04 at 1 58 46 pm](https://cloud.githubusercontent.com/assets/830932/19061242/d4a9e706-8a3a-11e6-89c2-5e44ac204de6.png)

Can you help?
Thanks! :)

**Comment by fatgue** [comment]
Simply change this 

> var (attributes, error) = options.attributes(key: nil, value: value)
if let error = error {
    print(error.localizedDescription)
    throw error
}

to:

> var (attributes, error) = options.attributes(nil, value: value)
            if let error = error {
                print(error.localizedDescription)
                throw error
            }

and:

> var (attributes, error) = options.attributes(key: key, value: value)
if let error = error {
    print(error.localizedDescription)
    throw error
}


to:

> var (attributes, error) = options.attributes(key, value: value)
            if let error = error {
                print(error.localizedDescription)
                throw error
            }

**Comment by kishikawakatsumi** [comment]
Maybe you run migrator to Keychain.swift? KeychainAccess 3.0.x already supports Swift 3. You do not need to convert for Keychain.swift.

Closing as duplicated to https://github.com/kishikawakatsumi/KeychainAccess/issues/273  and https://github.com/kishikawakatsumi/KeychainAccess/issues/272.

**Comment by solal** [comment]
Thanks, worked like a charm.
I saw you had support for Swift 3 so I didn't run the migrator for Keychain.swift. I just updated the version number in my `Podfile` to the correct version but still had this error.

**Comment by kishikawakatsumi** [comment]
@solal I confirmed built successfully. Maybe clean/build would resolve issue. Or could you share repro project?

**Comment by solal** [comment]
I ended up specifying the Swift version in the Podfile.

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
```

**Comment by solal** [comment]
Thanks for you help!
