### ISSUE TITLE
iOS version requirements 

### ISSUE THREAD

**Issue by Arrnas** [kishikawakatsumi/KeychainAccess#29]
the readme states that iOS7+ is required but the pod requires iOS8

**Comment by kishikawakatsumi** [comment]
To use Cocoa touch Framework, `Deployment Taget` must be 8.0 or later.
CocoaPods for Swift is the tool to build a framework.
CocoaPods require iOS 8 or later.

Carthage is also same.

If you use this library on iOS 7, add to your project manually.

**Comment by Arrnas** [comment]
thanks for the quick reply.
adding the project and frameworks doesn't work on iOS7 since dylibs are only supported on iOS8. the workaround for that is to just add the files to the project. After doing that i found that the set method with strings doesn't work on iOS7 because of line 345 in keychain.swift:

    query[kSecUseNoAuthenticationUI] = kCFBooleanTrue

here's how the code looks now:

    #if os(iOS)
    if (iOSVersion.getVersion() == .equalOrAbove8){
        query[kSecUseNoAuthenticationUI] = kCFBooleanTrue
    }
    #endif

    enum iOSVersion {
    case lowerThan8
    case equalOrAbove8
    static func getVersion() -> iOSVersion {
        switch UIDevice.currentDevice().systemVersion.compare("8.0.0", options: NSStringCompareOptions.NumericSearch) {
        case .OrderedSame, .OrderedDescending:
            return .equalOrAbove8
        case .OrderedAscending:
            return .lowerThan8
        }
      }
    }

because kSecUseNoAuthenticationUI only supports iOS8, so i just added a check to skip it if iOS version is lower than 7
there are also other keys that are not supported:

     @availability(iOS, introduced=8.0)
     var kSecAttrAccessibleWhenPasscodeSetThisDeviceOnly: CFStringRef

    @availability(iOS, introduced=8.0)
    var kSecUseOperationPrompt: CFStringRef
 
    @availability(iOS, introduced=8.0)
    var kSecUseNoAuthenticationUI: CFStringRef

    @availability(iOS, introduced=8.0)
    var kSecAttrAccessControl: CFStringRef

**Comment by kishikawakatsumi** [comment]
Oh...sorry, I try to fix it. Thanks.

**Comment by Arrnas** [comment]
no problem, thanks for releasing this, saved me a lot of time.

**Comment by kishikawakatsumi** [comment]
Fix https://github.com/kishikawakatsumi/KeychainAccess/pull/31

Could you please check it?

**Comment by Arrnas** [comment]
works great, thank you very much.
