### ISSUE TITLE
OSStatus error:[-50] with Xcode 8 and swift3

### ISSUE THREAD

**Issue by Dev-MJ** [kishikawakatsumi/KeychainAccess#290]
I make main app and today extension.
I'm using keychain for personal data.
so, when i save data in keychain, i did use Keychain(service: , accessGroup: ) and KeychainAccess ver 3.0.1

//save action
@IBAction func btnSave(_ sender: UIButton) {
     let keychain = Keychain(service: "ABC", accessGroup: "*")
         keychain[data: keyname] = NSData(data: UIImagePNGRepresentatioin(image)) as Data
}

//get list personal data
(in tableViewController)

let keychain = Keychain(service: "ABC", accessGroup: "*")

func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
    let cell = tableView.dequ.....
        cell.textLabel.text = "(keychain.allKeys()[indexPath.row])"
    return cell
}

sometimes, save data in keychain successfully and show data list. But when one or more data saved in keychain, i can't show data list and show this error message.
"osstatus error:[-50] One or more parameters passed to a function were not valid. "

**Comment by behdadahmadi** [comment]
I have this problem about 2 hours ago, I solved it this way:
`var keychain = Keychain(service: "com.example").accessibility(.whenPasscodeSetThisDeviceOnly, authenticationPolicy: .userPresence)`
```
DispatchQueue.main.async(execute: {
                do{
                    try self.keychain
                        .set(key2, key: hashedKey1)
                }catch let err{
                    print(err)
                }
            DispatchQueue.main.async(execute: { 
                print(self.keychain.allKeys())
            })
            })

```
NOTICE: You should execute `keychain.allKeys()` in a separated thread.

**Comment by nick3389** [comment]
same here with XCode 9. Is there any solution? I try to test some functions in a swift framework in my frameworks Test class and I constantly get this error.

**Comment by behdadahmadi** [comment]
@nick3389  Did you try my solution? My solution worked well when I tested it with Xcode 8.3.

**Comment by nick3389** [comment]
@behdadahmadi I will test it in a bit. Have you tried it in XCode 9?

**Comment by behdadahmadi** [comment]
@nick3389 No,I didn't try it yet in Xcode 9.

**Comment by nick3389** [comment]
@behdadahmadi It works when I test my framework from an app and that's how I will proceed for now. But I think it's better to work in a stand-alone framework project

**Comment by camfowler** [comment]
I'm also getting errors when running tests - very similar behaviour.

**Comment by behdadahmadi** [comment]
@camfowler Are you sure about executing your code on a separated thread?

**Comment by yairsz** [comment]
I solved this by enabling keychain sharing capability, as well as making sure that there was a Host Application set in the test target
<img width="447" alt="screen shot 2018-03-01 at 8 11 47 pm" src="https://user-images.githubusercontent.com/2353228/36878399-d15ba382-1d8c-11e8-88e4-0ea53eafaca9.png">

**Comment by kishikawakatsumi** [comment]
@yairsz is correct. Unit tests require host application. Because of needing device testing (Some  Keychain APIs is restricted on a simulator) and some APIs require entitlements such as sharing, touch ID and so on. If you're seeing the issue on only unit testing, it is expected.
