### ISSUE TITLE
Module compiled with Swift 3.0 cannot be imported in Swift 3.0.1

### ISSUE THREAD

**Issue by helloniklas** [kishikawakatsumi/KeychainAccess#291]
I keep getting Module compiled with Swift 3.0 cannot be imported in Swift 3.0.1 error despite trying to clean and remove everything and making sure Xcode select is set to latest Xcode 8.1.

**Comment by nanzhong** [comment]
Are you updating via carthage? If so adding `--no-use-binaries` to the update should resolve this.

**Comment by kishikawakatsumi** [comment]
@helloniklas 
@nanzhong is correct. Carthage attempts to use pre-built binary if it exists. `--no-use-binaries` forces building from source. I'll update Swift 3.0.1 compatible pre-built binary soon.
