### ISSUE TITLE
Swift 3.0.1 build, using Carthage

### ISSUE THREAD

**Issue by txaiwieser** [kishikawakatsumi/KeychainAccess#292]
I can help to update if you want, just need some directions.

**Comment by andre991** [comment]
+1

**Comment by terut** [comment]
@txaiwieser Maybe you can use `--no-use-binaries` option. I solved same problem by building the binary by myself.

**Comment by terut** [comment]
Maybe you can use `--no-use-binaries` option if you wanna fix soon. I solved same problem by building the binary by myself.

**Comment by andre991** [comment]
Ok terut, thanks it's working!

**Comment by kishikawakatsumi** [comment]
Closing duplicate of https://github.com/kishikawakatsumi/KeychainAccess/issues/291
