### ISSUE TITLE
Carthage error: Module compiled with Swift 3.0 cannot be imported in Swift 3.0.1

### ISSUE THREAD

**Issue by anfriis** [kishikawakatsumi/KeychainAccess#295]
The binary should be built with the newest version of Swift: 3.0.1

**Comment by nafu** [comment]
@Anders123fr 

You can use with `carthage update --no-use-binaries`

See @rad3ks's comment: https://github.com/kishikawakatsumi/KeychainAccess/pull/293#issuecomment-260373336

**Comment by Anders123fr** [comment]
Yes I know, but I still think that it should comply with the latest Swift version, 3.0.1 :)

**Comment by marbetschar** [comment]
Any news on this one?

**Comment by rad3ks** [comment]
I guess someone will do the release of newest version compiled with Swift 3.0.1, for now use `--no-use-binaries`

**Comment by LiborZ** [comment]
As others I am looking for version compiled with Swift 3.0.1. Thanks

**Comment by vittoriom** [comment]
I add myself to the list, and will even mention Swift 3.0.2 👍

**Comment by kgn** [comment]
It would be great to get this resolved, this is the only Carthage package I'm using that needs `--no-use-binaries` but using that flag means my updates take a long time as now all packages have to be built instead of downloaded.

**Comment by rad3ks** [comment]
I was just recently advised to use my own fork and upload my own binary for the release version I'm interested in. This way I'm able to point to KeychainAccess fork in Cartfile and not use `--no-use-binaries`. It's a great strategy to boost the `carthage bootstrap` speed.

To achieve that you should:
1. Fork this repo
2. Follow the [instructions](https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file)
3. Go to releases in your fork
4. Edit & upload the `KeychainAccess.framework.zip`
5. Use your fork in Cartfile

Unfortunately it's required to repeat those steps for each new release.

**Comment by gemedet** [comment]
+1

**Comment by kishikawakatsumi** [comment]
Please update Carthage to 0.20. Carthage uses pre-built binary only when they were built with the same version of the Swift compiler from 0.20. No longer need to `--no-use-binaries` :)
https://github.com/Carthage/Carthage/releases/tag/0.20.0

**Comment by nafu** [comment]
Cool 👍
