### ISSUE TITLE
Warnings in Console.app after enabling sandbox

### ISSUE THREAD

**Issue by ericdke** [kishikawakatsumi/KeychainAccess#297]
I recently sandboxed my application and since then this message appears in Console.app:

> not attempting migration for /Library/Keychains/System.keychain version 256 (0 0 1)  
> switching to keychain-db: /Users/me/Library/Keychains/login.keychain-db from /Users/me/Library/Keychains/login.keychain (0 1 1 1)  
> not switching as we're not in ~/Library/Keychains/: /Library/Keychains/System.keychain (0)  

*(the last two line are repeated several times, each time)*

But everythings works (thanks, btw!), same as before sandboxing.

Xcode 8.1, Swift 3, Cocoa app, macOS 10.12.1

Is it an issue with KeychainAccess and Sierra? Should I do something about it in my code or ignore it?

**Comment by kishikawakatsumi** [comment]
It seems not library side problem. If you have more information, feel free to reopen this issue. Thank you for reporting.
