### ISSUE TITLE
KeychainAccess values cannot be accessed by UICKeyChainStore

### ISSUE THREAD

**Issue by scalessec** [kishikawakatsumi/KeychainAccess#301]
Hey @kishikawakatsumi,

First off thanks for the useful libraries. I have an Objective-C app using `UICKeyChainStore` and a Swift app using `KeychainAccess`. The two apps are using a shared keychain to share data.

`KeychainAccess` can access data saved by `UICKeyChainStore`. The reverse, however, is not true -- `UICKeyChainStore` cannot access data saved by `KeychainAccess`.

I'm not sure if the issue is in `KeychainAccess`'s save methods or in `UICKeyChainStore`'s accessor methods but something is off somewhere.

Any thoughts as to why this may be the case?

**Comment by scalessec** [comment]
It's worth noting that I can easily reproduce by adding both libraries to one project (no need to have two apps).

**Comment by kishikawakatsumi** [comment]
@scalessec Both libraries just thin wrapper for the Keychain API. I believe both library can load the value from Keychain even if the value is saved by any ways. I think the setting is something different. Can you share the project to reproduce for investigation?
