### ISSUE TITLE
Compilation failure in Xcode 8.3 beta 1

### ISSUE THREAD

**Issue by ZevEisenberg** [kishikawakatsumi/KeychainAccess#306]
```
Pods/KeychainAccess/Lib/KeychainAccess/Keychain.swift:2054:19: error: redundant conformance of 'Status' to protocol 'RawRepresentable'
extension Status: RawRepresentable, CustomStringConvertible {
                  ^
Pods/KeychainAccess/Lib/KeychainAccess/Keychain.swift:1648:21: note: 'Status' declares raw type 'OSStatus' (aka 'Int32'), which implies RawRepresentable
public enum Status: OSStatus, Error {
```

Apple has [said](https://twitter.com/jckarter/status/825012717580726272) that any compilation failures in 8.3 betas should be considered bugs, so it's probably not your fault, but I thought you might want the chance to look into it. I'll most likely file a bug as well.

**Comment by tifroz** [comment]
I just tested with Xcode 8.3 beta 2, and seeing the same compilation issue as with the beta 1

**Comment by ZevEisenberg** [comment]
Filed a bug, and linked back here: http://openradar.me/30386658

**Comment by ZevEisenberg** [comment]
There's an open PR for Swift 3.1 that purports to fix this: https://github.com/apple/swift/pull/7345. I'm not set up to test my project against a dev build of Swift, but it's there in case someone wants to test it.

**Comment by kishikawakatsumi** [comment]
@ZevEisenberg Thank you for pointing it out. This issue was fixed by https://github.com/kishikawakatsumi/KeychainAccess/pull/303, but I keep the issue open to track the Xcode bug.

**Comment by FranciscoAmado** [comment]
Hi,

@kishikawakatsumi just to let you know that in Xcode 8.3 latest release, building through Carthage doesn't bring any error anymore, the [apple/swift#7345](https://github.com/apple/swift/pull/7345) was also merged in 9 Feb.

Thanks for the work 👍🏻
