### ISSUE TITLE
Case Sensitive Search

### ISSUE THREAD

**Issue by hons82** [kishikawakatsumi/KeychainAccess#308]
Hi,
in the [documentation](https://developer.apple.com/library/content/documentation/Security/Conceptual/keychainServConcepts/02concepts/concepts.html#//apple_ref/doc/uid/TP30000897-CH204-SW2) I've found that by setting _kSecMatchCaseInsensitive_ it is possible to perform a Case-Insensitive search on the keychain.
Is there a way to configure it in your Library as well?

**Comment by kishikawakatsumi** [comment]
@hons82 KeychainAccess doesn't support `kSecMatchCaseInsensitive`. I have no plan to support it. The workaround is converting a key to lowercase before save a value.
