### ISSUE TITLE
KeychainAccess don't clear when user delete application

### ISSUE THREAD

**Issue by AnhNH2512** [kishikawakatsumi/KeychainAccess#309]
I've got problem about store Keychain. When I delete application and reinstall, keychain sometime don't clear data. I can get old data from keychain. Are anyone face this issue?

**Comment by kishikawakatsumi** [comment]
@AnhNH2512 That's correct behavior. The data of the keychain keeps remaining even uninstalling the application. That is the specification. It is not a problem with the library.

**Comment by AnhNH2512** [comment]
@kishikawakatsumi : I got it. Thank you!
