### ISSUE TITLE
Carthage error: Module compiled with Swift 3.0 cannot be imported in Swift 3.0.2

### ISSUE THREAD

**Issue by cikpis** [kishikawakatsumi/KeychainAccess#314]
Hi Guys, I just got this error:
```
Error:(10, 8) module compiled with Swift 3.0 cannot be imported in Swift 3.0.2
```
Could you please do an hot-fix? Thanks in advance!

**Comment by kishikawakatsumi** [comment]
@cikpis Carthage just download pre-built binary by default. Use `carthage update --no-use-binaries` instead. See also https://github.com/kishikawakatsumi/KeychainAccess/pull/293#issuecomment-260373336

**Comment by cikpis** [comment]
@kishikawakatsumi that is not a valid answer. You should consider that a lot of devs don't use ```--no-use-binaries``` like https://github.com/kishikawakatsumi/KeychainAccess/issues/295

I just fixed it forking this repository and create a .zip file with carthage and put it on the root https://github.com/cikpis/KeychainAccess.

That's it :)
