### ISSUE TITLE
Keeping a secured Keychain instance opened 

### ISSUE THREAD

**Issue by txaiwieser** [kishikawakatsumi/KeychainAccess#315]
I have the following situation, I have a Touch-ID secured keychain and need to open get a key, modified this key and then adding-it again to the keychain.

The problem is the Touch-ID alert pops up both times, I would like to keep the keychain opened for a while, to complete this operations.

this is how i'm doing right now, keeping a property to capture it opened.

```swift
    // Keychain Access
    lazy var keychain: Keychain = {
        let k = Keychain(service: KEYCHAIN_KEY)
            .accessibility(.always, authenticationPolicy: .userPresence)
        return k
    }()
    
    private func loadUserCredentialsFromKeychainIfAvailable(completion: @escaping (_ accessToken: String?) -> Void) {
        DispatchQueue.global().async { [unowned self] in
            let token = try? self.keychain
                .get(KEYCHAIN_TOKEN_STRING)
            if let token = token { self._accessToken = token }
            DispatchQueue.main.async { completion(token ?? nil) }
        }
    }
    
    private func saveCredentialsOnKeychain(accessToken: String) {
        DispatchQueue.global().async { [unowned self] in
            try? self.keychain
                .set(accessToken, key: KEYCHAIN_TOKEN_STRING)
        }
    }
    
```

Any info would be awesome! Thanks for the great lib! 😄👍

**Comment by kishikawakatsumi** [comment]
@txaiwieser There is no API in Keychain API such stateful operations. In the Keychain API, there are some stateless CRUD methods, there is no concept of keeping keychain open.
