### ISSUE TITLE
Creating Application Password

### ISSUE THREAD

**Issue by harpangell7** [kishikawakatsumi/KeychainAccess#317]
I want to present the user with an application specific passcode that they can set if they chose to cancel on the touch ID or if they get the touch ID wrong and then decide to set a passcode. I know how to just set a passcode, but I cant figure out how to change the accessibility if they choose not to use the touch ID, or get it wrong. Any direction would be helpful. I've scanned the documentation bunch of times but Im obviously missing it. If someone could show me I would appreciate it.

**Comment by kishikawakatsumi** [comment]
@harpangell7  There is no API to set app specific or system passcode. Setting or changing passcode doesn't allow for us.
