### ISSUE TITLE
how can i use "Keychain.allKeys(.genericPassword)"

### ISSUE THREAD

**Issue by Dev-MJ** [kishikawakatsumi/KeychainAccess#324]
`OSStatus error:[-50] One or more parameters passed to a function were not valid. ` is displayed in console when I use `Keychain.allKeys(.genericPassword)`

**Comment by kishikawakatsumi** [comment]
@Dev-MJ Could you provide more info? What's OS version are you using? iPhone? macOS?

**Comment by Dev-MJ** [comment]
@kishikawakatsumi i'm using iphone and xcode8.3.2
when i using only that function, that error message was shown. :(

**Comment by ReaddyEddy** [comment]
It works for me Xcode 9.2
'''
let items = Keychain.allItems(.genericPassword)
'''

**Comment by kishikawakatsumi** [comment]
@Dev-MJ Probably your project doesn't set up Keychain sharing entitlements. `allItems()` requires it.
