### ISSUE TITLE
it returns optional(nil) while using "let token = try? keychain.get("key")"

### ISSUE THREAD

**Issue by apiapia** [kishikawakatsumi/KeychainAccess#327]
let keychain:Keychain
        let service = "com.xxyyzz-token"
        keychain = Keychain(service: service)
        let token = try? keychain.get("uuid")
        // MARK:- need to type token! ,cannot just type token,coz it always return optional(nil)
       // why does it happened?
        if token! != nil {
             
         }else {
            
        }

**Comment by kishikawakatsumi** [comment]
@apiapia Can you make sure you save a value before retrieving it? There is no code to save a value for `"uuid"` in above snippet. How did you save the value?

**Comment by kishikawakatsumi** [comment]
Closing due to no response.

**Comment by SylarRuby** [comment]
> @apiapia ..How did you save the value?

This pointed me in the right direction! I was doing

```swift
let keychain = Keychain(service: "My-Credentials")
keychain["access-id"] = res.number // can be optional
```

Now, I ensure `res.number` is present before saving (not shown) then

```swift
keychain["access-id"] = String(res.number!) // at this stage, res.number is not nil
```
