### ISSUE TITLE
Unresolved identifier error in swift 

### ISSUE THREAD

**Issue by kalyan711987kalyan** [kishikawakatsumi/KeychainAccess#328]
![screen shot 2017-06-26 at 1 11 20 pm](https://user-images.githubusercontent.com/1528160/27529226-55e2bd82-5a71-11e7-9e21-c885a25a62a1.png)

I'm getting following error. Can you please help me out.

**Comment by kishikawakatsumi** [comment]
@kalyan711987kalyan It seems you forgot `import KeychainAccess`

**Comment by kishikawakatsumi** [comment]
Closing due to no response.
