### ISSUE TITLE
Enter Password Prompt

### ISSUE THREAD

**Issue by mkkroliks** [kishikawakatsumi/KeychainAccess#329]
How can display "Enter Passcode" option in TouchID authentication prompt. It is visible on one of the images in documentation but I can't apply it in my app? Is there also any option to remove "Cancel" button in TouchID authentication prompt? Thanks

**Comment by kishikawakatsumi** [comment]
To enable fallback passcode, you need to specify `.userPresence` auth policy. It means it requires user presence policy using Touch ID or Passcode. Then a user failed touch id authentication once, the "Enter Passcode" button appears.

You cannot remove cancel button. Only Auth Policy can be customized (e.g. Touch ID only, Touch ID or passcode, or app password, etc). You can not customize the UI. 

Does it answer for you?

@mkkroliks
