### ISSUE TITLE
Keychain Access Group

### ISSUE THREAD

**Issue by petar-petrov** [kishikawakatsumi/KeychainAccess#330]
I am unable to access keychain group. After debugging for a while I discovered that the service is added to the query dictionary and that prevents it to access the keychain group. Please advice and I would like to ask if there are some know issues?

**Comment by kishikawakatsumi** [comment]
@petar-petrov Can you share your code? Access group's code is well tested. I believe there is something wrong in your code.

**Comment by kishikawakatsumi** [comment]
Closing due to no response. Please feel free to reopen if you can provide more info.
