### ISSUE TITLE
Missing Documentation and interface

### ISSUE THREAD

**Issue by racer1988** [kishikawakatsumi/KeychainAccess#339]
Hello,

as an improvement, I think it would be interesting to have documentation on each `Keychain` function, to explain what the function does, and why it throws if it does.

Also, for the sake of testability, it would be interesting to move all documentation in a public interface that Keychain replicate. This way it would also provide ways of using this framework, but mock the Keychain if needed for testing inside a third party app, by creating a mock based on the interface

**Comment by alexchernokun** [comment]
+1

**Comment by kishikawakatsumi** [comment]
Contribution is welcome 😁
