### ISSUE TITLE
Xcode 9 beta 6 - Module compiled with Swift 3.1 cannot be imported in Swift 3.2

### ISSUE THREAD

**Issue by olsamaja** [kishikawakatsumi/KeychainAccess#340]
Hi there,

Building with Xcode 9 beta 6 my app fails due to unsupported Swift 3.1 (fyi, I imported KeychainAccess in a private framework).

Could you please rebuild the lib using Xcode 9 / Swift 3.2 ?

Thanks

**Comment by kishikawakatsumi** [comment]
I don't publish prebuilt binary frameworks built with prerelease versions of Xcode as there's no guarantee of compatibility between beta versions. Prebuilt binary frameworks for Swift 3.2 will be available after Xcode 9 is out of beta.

For now, the recommended means of using KeychainAccess with beta versions of Xcode 9 is to build it from source. CocoaPods and Carthage are the easiest ways to do this as they either always build from source (CocoaPods) or will automatically fall back to building from source if the prebuilt binary is from a different Swift version (Carthage).

**Comment by olsamaja** [comment]
Hi, 

I followed your suggestions and built the lib from source to test Xcode 9. 
Many thanks ;-)
