### ISSUE TITLE
Reading old Keychain entries

### ISSUE THREAD

**Issue by damirstuhec** [kishikawakatsumi/KeychainAccess#343]
Hi there! Up until now, we were using the old Apple-provided `KeychainItemWrapper` (https://gist.github.com/dhoerl/1170641) in our project.

We were storing/reading a simple "Touch ID"-like PIN code with the following API:

```
// Reading
[self.keychainItem objectForKey:(__bridge id)kSecAttrAccount];
// Storing
[self.keychainItem setObject:passcode forKey:(__bridge id) kSecAttrAccount];
```

We would like to migrate from using the old wrapper to this library but we cannot extract the existing values using Keychain.

The strange thing is that when we `print` an instance of `Keychain`, the value (PIN code) is indeed there and printed, but we cannot figure out how to extract its value.

This is the console output of `print(keychain)` where `"acct": 1012` is the actual value, previously saved with the `KeychainItemWrapper`, that we are trying to extract:

```
["persistref": <>, "mdat": 2017-09-11 19:11:00 +0000, "acct": 1012, "sync": 0, "svce": , "gena": PINKey, "pdmn": ak, "v_Data": <>, "tomb": 0, "desc": , "agrp": [redacted], "labl": , "cdat": 2017-09-11 19:11:00 +0000, "sha1": <[redacted]>, "musr": <>]
```

Any ideas? Thanks.
cc @kishikawakatsumi

**Comment by kishikawakatsumi** [comment]
Thanks for sending the repro case. You are misunderstanding Keychain API or QIKeychainItemWrapper is broken. `acct` (=kSecAttrAccount) isn't a value... So the `123` isn't encrypted. Keychain API saves values with `service+group+account` as unique keys. You have made only the key, but you do not save the value. There is no way to retrieve `kSecAttrAccount` in KeychainAccess lib. You should migrate it using raw Keyhchain API.
