### ISSUE TITLE
Support for Face ID

### ISSUE THREAD

**Issue by BennX** [kishikawakatsumi/KeychainAccess#344]
I couldn't find anything for copy/updating an entry with face ID authentication. Is there anything required to support it or is the OS already handling that with the current query values?

Any plans to support Face ID instead of Touch ID when the device is capable of it?

**Comment by kishikawakatsumi** [comment]
@BennX I don't find face ID specific API in Keychain services. Local Authentication API has `biometryType` as readonly property. So I assume requiring touch ID falls back face ID UI automatically by iOS. Probably we don't need to do anything to support face ID.

**Comment by petrdvorak** [comment]
@kishikawakatsumi ... the situation seems to be worse. From what I have found in the API docs and after checking with the miraculous internet, Apple has added FaceID support for LocalAuthentication framework, but not to Keychain APIs. Testing with simulator seems to confirm this so far for us, hopefully we will get some good news when we have a new device in our hands...

**Comment by BennX** [comment]
There is a post of a Apple dev that says:
>FaceID does not work in the Xcode 9 GM due to a framework bug.
 >
>For now the best thing to do is to test on an iPhone 8 and ensure everything works with Touch ID.

https://forums.developer.apple.com/thread/86779

**Comment by petrdvorak** [comment]
@BennX Thank you

**Comment by svdo** [comment]
Hi guys, I'd like to ask that this issue is reopened. By now Face ID works, so I don't see a reason why this project cannot support it. I'm not getting an ugly warning on iPhone X: "This app was designed to support Touch ID. It has not been updated for Face ID." Thanks!

**Comment by petrdvorak** [comment]
@svdo You need to put NSFaceIDUsageDescription in your Info.plist...

**Comment by svdo** [comment]
Ah, I was looking in the wrong direction, thank you!
