### ISSUE TITLE
Conversion to Swift 4 warning

### ISSUE THREAD

**Issue by iosdeveloper** [kishikawakatsumi/KeychainAccess#348]
I get a warning to convert to Swift 4 using KeychainAccess.xcproj as a submodule. If I try to ignore it, the submodule is changed (see diff). Can this be included in #337 as it seems to be a simple fix?

```
$ cd KeychainAccess
$ git diff
diff --git a/Lib/KeychainAccess.xcodeproj/project.pbxproj b/Lib/KeychainAccess.xcodeproj/project.pbxproj
index ed1b1ab..c9730b7 100644
--- a/Lib/KeychainAccess.xcodeproj/project.pbxproj
+++ b/Lib/KeychainAccess.xcodeproj/project.pbxproj
@@ -272,14 +272,17 @@
                                TargetAttributes = {
                                        140F195B1A49D79400B0016A = {
                                                CreatedOnToolsVersion = 6.1.1;
+                                               LastSwiftMigration = 0900;
                                                ProvisioningStyle = Automatic;
                                        };
```

**Comment by kishikawakatsumi** [comment]
macOS build that is generated by Xcode 8.3 and Xcode 9 doesn't work correctly on Travis CI. #337 cannot be merged unless solving the issue.

**Comment by iosdeveloper** [comment]
That is really unfortunate because it means we have to live with two warnings because of this project or replace it entirely.

**Comment by kishikawakatsumi** [comment]
@iosdeveloper Probably https://stackoverflow.com/a/13209057/1733883 help?

**Comment by iosdeveloper** [comment]
As I said initially, I‘m adding dependencies manually.
