### ISSUE TITLE
OSStatus error:[-50] One or more parameters passed to a function were not valid.

### ISSUE THREAD

**Issue by ugenlik** [kishikawakatsumi/KeychainAccess#354]
iOS 11, Swift 4.0 , simulator iphone 6

This function works fine when compiled and deployed to the actual device or run in simulator

```
    func saveAccessToken(accessToken:String )
    {
        do {
            try keychain.set(accessToken, key: .keyChainAccessToken)
        }
        catch let error {
            log.severe("Saving access token to keychain failed = \(error)")
        }
    }
```

However, my unit tests started failing after upgrading to Xcode 9.

**OSStatus error:[-50] One or more parameters passed to a function were not valid.**

Any idea how to solve this?

**Comment by kishikawakatsumi** [comment]
@ugenlik I need more information to answer your question. Can you share more details? How the `keychain` instance did you initialize? What parameters did you pass?

**Comment by AlTavares** [comment]
I'm having the same issue, apparently it only happens when running unit tests.
I'm initializing the keychain instance passing only the service:

`let keychain = Keychain(service: "myService")`

**Comment by AlTavares** [comment]
It happens when running tests without a Host Application

**Comment by ugenlik** [comment]
@kishikawakatsumi 

There is nothing I do extra, like @AlTavares said, when I run it without a host application, my unit tests fail for `let chain = Keychain(service: "ServiceName")` then `saveAccessToken(accessToken:)`

my unit test is trying to save a string I get from our login server. in the actual app target or device it works fine , in unit test without host I get

**Saving access token to keychain failed = One or more parameters passed to a function were not valid.**

here is the full log from the xcode

[keychaintestlog.txt](https://github.com/kishikawakatsumi/KeychainAccess/files/1451297/keychaintestlog.txt)

**Comment by kishikawakatsumi** [comment]
@ugenlik @AlTavares The issue appears only on unit testing without host app, right. If so, it is expected. KeychanAccess requires host app and valid entitlement even on unit testing. Because it supports many app dependent features, like touch ID, iCloud sharing etc.

**Comment by ugenlik** [comment]
@kishikawakatsumi it is interesting because it used to work pre-XCode 9, no code changes... But okay will close the issue...
