### ISSUE TITLE
Can't build on Xcode 9.1

### ISSUE THREAD

**Issue by yuumi3** [kishikawakatsumi/KeychainAccess#357]
XXXXX.swift:10:8: Module compiled with Swift 4.0 cannot be imported in Swift 4.0.2: /YYYYY/ZZZZ/Carthage/Build/iOS/KeychainAccess.framework/Modules/KeychainAccess.swiftmodule/x86_64.swiftmodule

**Comment by kishikawakatsumi** [comment]
@yuumi3 Use `carthage update --no-use-binaries` or update Carthage to higher than 0.20. 

Carthage only supports using prebuilt binaries for a single version of Xcode. Currently KeychainAccess' prebuilt binaries are built with Xcode 9.0. If the version of Xcode you're using differs from the version used to build the prebuilt binaries, Carthage that is higher than 0.20 will detect this, and fall back to building Realm from source. The end result should still be working KeychainAccess frameworks.

**Comment by yuumi3** [comment]
Thanks!
