### ISSUE TITLE
Keychain shared across apps with similar app id's

### ISSUE THREAD

**Issue by crspybits** [kishikawakatsumi/KeychainAccess#358]
I doubt this will end up being anything about your pod, but here's what I'm finding:
https://stackoverflow.com/questions/47272209/sharing-of-keychain-values-across-apps-with-similar-bundle-ids

**Comment by kishikawakatsumi** [comment]
You need to enable Keychain sharing capability.

**Comment by crspybits** [comment]
You may have missed the point... I was getting this sharing behavior *without* enabling sharing.
