### ISSUE TITLE
No way to retrieve key AND password associated with an app?

### ISSUE THREAD

**Issue by theblixguy** [kishikawakatsumi/KeychainAccess#367]
You can store a "key" and an associated "password". But in order to retrieve the password, you also need to know the key. Why isn't there a way to retrieve a key and password both, associated with an application, securely (Touch/Face ID or passcode)? I am building an app that stores the username and password in Keychain, and whenever the user opens the app, I want to retrieve the stored username and password so the user doesn't have to fill it in every-time they open the app, but I don't see a way to do it.

**Comment by kishikawakatsumi** [comment]
I don't understand what you'd like to do correctly. Can you elaborate a bit more? Probably does `allKeys` or `allValues` work for you?

**Comment by kishikawakatsumi** [comment]
Closing due to no response. Feel free to reopen if you have further information.
