### ISSUE TITLE
Missing Contents.swift File for Playground

### ISSUE THREAD

**Issue by MacMeDan** [kishikawakatsumi/KeychainAccess#370]
When Downloading the project and trying to access the Playground example you get hit with this 
![screen shot 2018-02-02 at 10 25 57 am](https://user-images.githubusercontent.com/6182351/35746306-9d3d5346-0803-11e8-8085-870642cacb40.png)

**Comment by kishikawakatsumi** [comment]
Closing due to https://github.com/kishikawakatsumi/KeychainAccess/pull/377
