### ISSUE TITLE
v3.1.1 Mac binary is wrong packaged

### ISSUE THREAD

**Issue by tualatrix** [kishikawakatsumi/KeychainAccess#378]
If you unpack the https://github.com/kishikawakatsumi/KeychainAccess/releases/download/v3.1.1/KeychainAccess.framework.zip, check the Mac version, you will find the framework is wrong packaged.

The files should be symbol linked from the Versions/Current, not copy as normal files.

Or code-sign will be failed. See: https://developer.apple.com/library/content/technotes/tn2206/_index.html#//apple_ref/doc/uid/DTS40007919-CH1-TNTAG313

**Comment by kkishikawa-folio** [comment]
@tualatrix Thanks. I'll fix it soon

**Comment by kishikawakatsumi** [comment]
Fixed
