### ISSUE TITLE
Question about using multiple services / keychain instances

### ISSUE THREAD

**Issue by RamblinWreck77** [kishikawakatsumi/KeychainAccess#379]
Hello!

When you configure multiple keychain instances with different service IDs, are they completely independent? 

Lets say I wake up in the background often (significant location change) and want to keep a simple token in an .always keychain, and keep user password/email in a .whenUnlocked keychain. 

```
let secureKeychain = Keychain(service: "com.example.com-secure").accessibility(.whenUnlocked)

let cacheKeychain = Keychain(service: "com.example.com-cache").accessibility(.always)

```

If my keychain manager class has two separate instances could they potentially interfere, or is this safe to do? 

Thanks in advance for any help!

**Comment by kishikawakatsumi** [comment]
@RamblinWreck77 Yes. Two instances work independently, it's safe to do so.
