### ISSUE TITLE
How to pass the server/domain as nil

### ISSUE THREAD

**Issue by mohammad19991** [kishikawakatsumi/KeychainAccess#386]
Is there a way not to pass the server? because `SecRequestSharedWebCredential` will read directly from the app `entitlements`

**Comment by kishikawakatsumi** [comment]
@mohammad19991 Just invoke `requestSharedWebCredential()` with no argument, like the following:

```
Keychain.requestSharedWebCredential { (credentials, error) in
    ...
}
```
