### ISSUE TITLE
Carthage issue building with swift 4.1.2

### ISSUE THREAD

**Issue by DrAma999** [kishikawakatsumi/KeychainAccess#389]
Hello there,
while checking out the project using Carthage with Xcode 9.4.1 I'm receiving this error:

> *** Skipped installing KeychainAccess.framework binary due to the error:
> 	"Incompatible Swift version - framework was built with 4.1 (swiftlang-902.0.48 clang-902.0.37.1) and the local version is 4.1.2 (swiftlang-902.0.54 clang-902.0.39.2)."

**Comment by kishikawakatsumi** [comment]
@DrAma999 This is not an error. Carthage only supports prebuilt binaries for a single Xcode version at a time. If you're using the latest version of Carthage, it will display this message and fall back to building KeychainAccess from source.

**Comment by DrAma999** [comment]
Thank you! I close the issue.
