### ISSUE TITLE
Cocoapods unknown option character `X' in: -Xlinker

### ISSUE THREAD

**Issue by mathiasmaehlum** [kishikawakatsumi/KeychainAccess#39]
Im getting an error after I install via Cocoapods:

error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: unknown option character `X' in: -Xlinker

Libtool /Users/Mathias/Library/Developer/Xcode/DerivedData/Orb-gabuteysqfjkydacbhuayztonsub/Build/Products/Debug-iphonesimulator/libPods-Orb-KeychainAccess.a normal x86_64
    cd /Users/Mathias/Desktop/Orb/Pods
    export IPHONEOS_DEPLOYMENT_TARGET=8.1
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static -arch_only x86_64 -syslibroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.1.sdk -L/Users/Mathias/Library/Developer/Xcode/DerivedData/Orb-gabuteysqfjkydacbhuayztonsub/Build/Products/Debug-iphonesimulator -filelist /Users/Mathias/Library/Developer/Xcode/DerivedData/Orb-gabuteysqfjkydacbhuayztonsub/Build/Intermediates/Pods.build/Debug-iphonesimulator/Pods-Orb-KeychainAccess.build/Objects-normal/x86_64/Pods-Orb-KeychainAccess.LinkFileList -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -Xlinker -add_ast_path -Xlinker /Users/Mathias/Library/Developer/Xcode/DerivedData/Orb-gabuteysqfjkydacbhuayztonsub/Build/Intermediates/Pods.build/Debug-iphonesimulator/Pods-Orb-KeychainAccess.build/Objects-normal/x86_64/Pods_Orb_KeychainAccess.swiftmodule -framework Foundation -o /Users/Mathias/Library/Developer/Xcode/DerivedData/Orb-gabuteysqfjkydacbhuayztonsub/Build/Products/Debug-iphonesimulator/libPods-Orb-KeychainAccess.a

error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: unknown option character `X' in: -Xlinker
Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-sacLT] [-no_warning_for_no_symbols]
Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -dynamic [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-o output] [-install_name name] [-compatibility_version #] [-current_version #] [-seg1addr 0x#] [-segs_read_only_addr 0x#] [-segs_read_write_addr 0x#] [-seg_addr_table <filename>] [-seg_addr_table_filename <file_system_path>] [-all_load] [-noall_load]

I have other pods in my podfile that works. Not sure what happened here

Cheers!

**Comment by kishikawakatsumi** [comment]
Are you sure to use beta version of CocoaPods?
To install Swift framework, requires to use pre release version of CocoaPods 0.36beta1.

http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/
