### ISSUE TITLE
Compile error with Xcode 10 Beta 4 (10L213o)

### ISSUE THREAD

**Issue by lvandal** [kishikawakatsumi/KeychainAccess#392]
Hi,

This is a follow up to issue #391. The actual issue is that there seems to be a missing watchOS simulator, which causes the compile to fail:

`*** Building scheme "KeychainAccess" in KeychainAccess.xcworkspace Build Failed Task failed with exit code 70: /usr/bin/xcrun xcodebuild -workspace /[...]/Vendor/Carthage/Checkouts/KeychainAccess/KeychainAccess.xcworkspace -scheme KeychainAccess -configuration Release -derivedDataPath /Users/[...]/Library/Caches/org.carthage.CarthageKit/DerivedData/10.0_10L213o/KeychainAccess/v3.1.1 -sdk watchsimulator -destination platform=watchOS\ Simulator,id=31C70040-2499-4CD8-802B-1952F7564EF2 -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /[...]/Vendor/Carthage/Checkouts/KeychainAccess)`

Here's an excerpt of the generated log file:

`xcodebuild: error: Unable to find a destination matching the provided destination specifier: { platform:watchOS Simulator, id:31C70040-2499-4CD8-802B-1952F7564EF2 } The requested device could not be found because no available devices matched the request.`

Specifying the platform (iOS or macOS) for the `--platform` parameter will let the code compile, just not for watchOS.

[carthage-xcodebuild.QCWWsc.txt](https://github.com/kishikawakatsumi/KeychainAccess/files/2207536/carthage-xcodebuild.QCWWsc.txt)

**Comment by kishikawakatsumi** [comment]
@lvandal I can reproduce this issue too. But it seems Carthage issue. I think that I can not fix it on my side.
