### ISSUE TITLE
Swift 5 support

### ISSUE THREAD

**Issue by lvandal** [kishikawakatsumi/KeychainAccess#410]
Xcode 10.2 Beta now comes with Swift 5. Any plans on updating KeychainAccess to support it? Thanks!

**Comment by jlaws** [comment]
## Expected Results

No warning to convert KeychainAccess.framework to Swift 5

## Actual Results

Xcode created warnings to convert KeychainAccess.framework to Swift 5

## Steps to Reproduce

Build the cocoapod in Xcode 10.2

**Comment by kishikawakatsumi** [comment]
https://github.com/kishikawakatsumi/KeychainAccess/pull/419

**Comment by jlaws** [comment]
Thanks for the quick turnaround!
