### ISSUE TITLE
Saved Password not in Autofill password

### ISSUE THREAD

**Issue by detectedstealth** [kishikawakatsumi/KeychainAccess#416]
Just found this framework, the situation I am able to save the keychain password and login with it. However when someone then logs out the keyboard shows the "Passwords" icon for auto fill passwords the app password isn't in that list. How would I get the app specific password in that list?

**Comment by kishikawakatsumi** [comment]
@detectedstealth See https://github.com/kishikawakatsumi/KeychainAccess#shared_web_credentials

**Comment by detectedstealth** [comment]
@kishikawakatsumi thanks however my comment was from 7 month ago. I have switched to using apple’s own password autofill now.
