### ISSUE TITLE
Xcode 6.3 bata new Swift support

### ISSUE THREAD

**Issue by 441088327** [kishikawakatsumi/KeychainAccess#42]
rt

**Comment by kishikawakatsumi** [comment]
Working on [swift_12](https://github.com/kishikawakatsumi/KeychainAccess/tree/swift_12) branch.

**Comment by pranavss11** [comment]
Now that Xcode 6.3 is live, will you be merging these changes in?

**Comment by prefect42** [comment]
Yes?

**Comment by evenh** [comment]
Looking forward to 1.2 support :+1: – keep up the good work!

**Comment by kishikawakatsumi** [comment]
I will release in Today. I'm working final check.

**Comment by kimar** [comment]
Ah, sorry I've not seen your `swift_12` branch but nevertheless, instead of casting the constants `as String` you could also just modify the returntype to `NSString`, check out my PR: https://github.com/kishikawakatsumi/KeychainAccess/pull/56

**Comment by skyem** [comment]
I'm using the swift_12 branch with Carthage in Xcode 6.3 but am still getting build failures when Carthage tries to build it. It appears the build failures are only on the Mac target. Is there a way to specify just the iOS target in the cartfile?

**Comment by kishikawakatsumi** [comment]
I shipped version 1.2.0! Compatible with Xcode 6.3 and Swift 1.2!! :tada:
