### ISSUE TITLE
Keychain save error

### ISSUE THREAD

**Issue by izabekz** [kishikawakatsumi/KeychainAccess#420]
I'm getting error when trying to save in Keychain that says: "The user name or passphrase you entered is not correct." What does that mean and how to solve it? Thanks!

**Comment by rafabertholdo** [comment]
I'm facing this error. Does anyone know how to solve it?

**Comment by EthanLipnik** [comment]
Any solution? Seems to only happen in the Simulator for me

**Comment by wuharvey** [comment]
Also have run into this issue - any leads would be much appreciated!

**Comment by Rendel27** [comment]
I'm facing with this issue on iOS 15 simulator.
Did anyone solve this issue?
