### ISSUE TITLE
Unit tests fail with Xcode 11 when running on iOS 13 Simulator

### ISSUE THREAD

**Issue by woolie** [kishikawakatsumi/KeychainAccess#437]
`func testSetAttributes()` tests fail running on iOS 13 (Xcode 11 beta 7).
If you select an iOS 12.2 simulator then the tests all pass.

**Comment by ibru** [comment]
Hi, I have an issue which is probably related to this one.
If I write data into keychain protected by TouchID (`keychain.accessibility(.whenPasscodeSetThisDeviceOnly, authenticationPolicy: .userPresence)`) they are failing to be retrieved back in iOS 13 simulator. But works in iOS 12 simulator. When I removed ` authenticationPolicy: .userPresence` it worked correctly in iOS 13.
Looks like new simulator has changed some behavior related to TouchID. Unfortunately, I dont have iOS 13 device, cannot say if its issue only with simulator or not.
Have you had a chance to look into this issue?
