### ISSUE TITLE
Keychain access group on macOS

### ISSUE THREAD

**Issue by itsdamslife** [kishikawakatsumi/KeychainAccess#438]
Keychain access group on macOS does not work. Apple recommends either to use iCloud sharing or Access control List. Since enterprise solution users mostly never login iCloud on work systems the only option is adding needed apps to Access Control List.

I have not seen any APIs for adding my apps to the Access Control List on macOS keychain item. Please help.

**Comment by jeff-h** [comment]
When you say "Keychain access group on macOS does not work." do you mean generically, this never works no matter what framework is used (or when none is used), or do you mean it doesn't work when using KeychainAccess?

With KeychainAccess I also cannot get it working (haven't tried any other Keychain framework). I have a macOS app that contains an embedded AskPass binary which should access the same keychain items as the main app, but currently I am prompted by the macOS Keychain to give both of them access manually.

Is my issue at https://github.com/kishikawakatsumi/KeychainAccess/issues/382 related to your issue?

**Comment by jeff-h** [comment]
Unfortunately it's macOS 10.15+ but the following seems pretty relevant: https://developer.apple.com/documentation/security/ksecusedataprotectionkeychain:

> Items that you store or have stored in macOS with the kSecAttrSynchronizable attribute set to true also behave like iOS keychain items. However, a true value for that attribute additionally causes iCloud to synchronize the item across all the user’s devices. Use kSecUseDataProtectionKeychain to get the iOS behavior without synchronization.

**Comment by itsdamslife** [comment]
You are right, Keychain access groups works on macOS only if iCloud Keychain sharing and Data protection flag enabled. Even on 10.15+ only Catalyst ported apps will be able to take advantage of Keychain Access  Groups.

I resolved my issue by using directly the keychain APIs from CoreServices framework.

**Comment by nevinjethmalani** [comment]
Can you clarify how I would get this to work? I am seeing a bunch of error when I try to enable MacOS on my app. This is one of the errors: 'kSecSharedPassword' is unavailable in Mac Catalyst
