### ISSUE TITLE
KeychainAccess not compatible with iOS7 ? 

### ISSUE THREAD

**Issue by thecritic** [kishikawakatsumi/KeychainAccess#44]
In the docs it says this wrapper can be used in iOS7, however, when I try to install it in CocoaPods it says: 

> [!] The platform of the target `XXX` (iOS 7.0) is not compatible with `KeychainAccess (1.1.1)` which has a minimum requirement of iOS 8.0 - OS X 10.9.

Is it true that it is only available on iOS8 and above ?

**Comment by kishikawakatsumi** [comment]
See https://github.com/kishikawakatsumi/KeychainAccess/issues/29

> To use Cocoa touch Framework, Deployment Taget must be 8.0 or later.
> CocoaPods for Swift is the tool to build a framework. CocoaPods require iOS 8 or later.
> Carthage is also same.
> If you use this library on iOS 7, add to your project manually.
