### ISSUE TITLE
Could not locate installed application Install claimed to have succeeded

### ISSUE THREAD

**Issue by astroboy0803** [kishikawakatsumi/KeychainAccess#456]
today, My Colleague and I are carthage update for our project.

build our project is OK, but can't install device 

we replace old framework step by step, and found out KeychainAccess.framework cause the error.

Xcode alert message: Could not locate installed application Install claimed to have succeeded

Xcode 11.1
KeychainAccess tag: v3.2.1

**Comment by David2XN** [comment]
I've had same problem with Xcode 11.1. I had to downgrade from 4.1.0 back to 3.2.0.

**Comment by kishikawakatsumi** [comment]
@astroboy0803 @David2XN It happens on Xcode 11.x. If you use Carthage to build the framework, ensure to select "Do not embed" and let `carthage copy-frameworks` to copy the framework.

<img width="681" alt="Screen Shot 2019-11-01 at 6 07 08" src="https://user-images.githubusercontent.com/40610/67986369-3bb79580-fc6e-11e9-8679-4e3ae76101a6.png">


<img width="694" alt="Screen Shot 2019-11-01 at 6 07 25" src="https://user-images.githubusercontent.com/40610/67986378-3eb28600-fc6e-11e9-9472-6a6cf9a0ee32.png">

**Comment by omerberger** [comment]
Are you using XCFrameworks: 'Build Libraries for Distribution' : true

**Comment by astroboy0803** [comment]
app crash when I select "Do not embed"

crash information:

dyld: Library not loaded: @rpath/KeychainAccess.framework/KeychainAccess
Referenced from: /var/containers/Bundle/Application/91E6A10C-BB51-4CBF-8B45-63BF104049CC/MyProject.app/MyProject

Reason: image not found

**Comment by kishikawakatsumi** [comment]
@astroboy0803 You said you are using Carthage. If so, you should use `copy-frameworks` to embed the framework to the app.

See https://github.com/Carthage/Carthage#quick-start

**Comment by astroboy0803** [comment]
I don't know why my way has error.

1. I use command line tool create Framework
   
<img width="370" alt="image" src="https://user-images.githubusercontent.com/9603201/69618702-4ac71300-1075-11ea-8d19-07a6d3111a0b.png">

2. "Build Phase > Link Binary With Libraries" add framework 

<img width="1218" alt="image" src="https://user-images.githubusercontent.com/9603201/69619195-29b2f200-1076-11ea-9745-4f653c09786e.png">

3. "Build Phase > Embed Frameworks"

<img width="1254" alt="image" src="https://user-images.githubusercontent.com/9603201/69619272-50712880-1076-11ea-952d-8cba9e347d4f.png">

**Comment by kishikawakatsumi** [comment]
@astroboy0803 Do not add to embed framework area. If you use Carthage, just only link the frameworks in Xcode GUI. Use the copy-framework script provided Carthage to embed and sign frameworks instead.

**Comment by kishikawakatsumi** [comment]
This is Carhtage side issue. The way to fix the issue is use `copy-framework` to embed the framework as following Carthage's instruction https://github.com/Carthage/Carthage#adding-frameworks-to-an-application
