### ISSUE TITLE
Obtaining multiple items with only a single authentication

### ISSUE THREAD

**Issue by TRCarbone** [kishikawakatsumi/KeychainAccess#463]
I'm obtaining a username as follows:

let keychain = Keychain(service: "com.example.github-token")

DispatchQueue.global().async {
    do {
        let username = try keychain
            .authenticationPrompt("Authenticate to login to server")
            .get("username")
    } catch let error {
        // Error handling if needed...
    }
}

Now I want to obtain both a username and a password as follows:

DispatchQueue.global().async {
    do {
        let username = try keychain
            .authenticationPrompt("Authenticate to login to server")
            .get("username")
        let password = try keychain
            .authenticationPrompt("Authenticate to login to server")
            .get("password")
    } catch let error {
        // Error handling if needed...
    }
}

This requires the user to authenticate with Touch ID or Face ID twice. How can I obtain multiple items with only a single authentication?

**Comment by kishikawakatsumi** [comment]
Probably you can pass `touchIDAuthenticationAllowableReuseDuration` with `LAContext` via `Keychain.authenticationContext(_:)` method.
