### ISSUE TITLE
Mac OS catalyst ported app fails to build due to 'SecAddSharedWebCredential' is unavailable: not available on macCatalyst

### ISSUE THREAD

**Issue by n3at18** [kishikawakatsumi/KeychainAccess#464]
Hello!

I'm trying to enable "Mac" switch so my iPad app can run on Mac as well but unfortunately it fails to build due to the following problems with KeychainAccess:

'SecAddSharedWebCredential' is unavailable: not available on macCatalyst
'SecRequestSharedWebCredential' is unavailable: not available on macCatalyst
'SecCreateSharedWebCredentialPassword' is unavailable: not available on macCatalyst
'kSecSharedPassword' is unavailable: not available on macCatalyst

I'm using the latest version of KeychainAccess available via CocoaPods '4.1.0'

Could you please suggest?

Thank you!

**Comment by kishikawakatsumi** [comment]
CocoaPods doesn’t support MacCatalyst yet.
XCFramework support has been merged yesterday https://github.com/CocoaPods/CocoaPods/pull/9334 . This makes CocoaPods support MacCatalyst. Meanwhile, you can use Carthage instead.

**Comment by n3at18** [comment]
> CocoaPods doesn’t support MacCatalyst yet.
> XCFramework support has been merged yesterday [CocoaPods/CocoaPods#9334](https://github.com/CocoaPods/CocoaPods/pull/9334) . This makes CocoaPods support MacCatalyst. Meanwhile, you can use Carthage instead.

Awesome, thanks for a quick response!

As I understand, after the next CocoaPods update we'll be able to use KeychainAccess with CocoaPods to build Mac apps

If yes - I can wait then

Thanks!

**Comment by GiacomoLeopizzi** [comment]
Hi!
I use the Swift Package Manager to include the package and I cannot also build because of the same error. I think that a solution would be to include a 

```
#if !targetEnvironment(macCatalyst)

#endif
```

around the code that use one of the above mentioned elements.

Regards,
Giacomo

**Comment by SMartorelli** [comment]
I need it too!
Best,
Simone
