### ISSUE TITLE
Package Resolution Failed in Xcode 11

### ISSUE THREAD

**Issue by rezamagnet** [kishikawakatsumi/KeychainAccess#469]

**Comment by peterthomashorn** [comment]
The package cannot be added to a project for a reason not visible in the user interface.

    The package dependency graph can not be resolved; unable find any available tag for the following requirements:

I was thinking the Git tags prefixed with "v" might be the culprit. Version information can be specified in Xcode in semantic versions only while the repository has all version tags prefixed with a nonconforming letter.
