### ISSUE TITLE
`APPLICATION_EXTENSION_API_ONLY = YES`

### ISSUE THREAD

**Issue by norio-nomura** [kishikawakatsumi/KeychainAccess#47]
`APPLICATION_EXTENSION_API_ONLY = YES` can prevent following warning when using KeychainAccess from App Extension project.

> ld: warning: linking against dylib not safe for use in application extensions: …Carthage/Build/iOS/KeychainAccess.framework/KeychainAccess

**Comment by kishikawakatsumi** [comment]
Done https://github.com/kishikawakatsumi/KeychainAccess/pull/48

**Comment by kishikawakatsumi** [comment]
Released version 1.1.2 that includes this fix. https://raw.githubusercontent.com/CocoaPods/Specs/24e682300e3c6c3bdc75136a687cc83ce9904867/Specs/KeychainAccess/1.1.2/KeychainAccess.podspec.json

**Comment by norio-nomura** [comment]
I confirmed that KeychainAccess 0.7.1 has been built with `APPLICATION_EXTENSION_API_ONLY = YES` for iOS and OS X targets by using Carthage.
Thanks!
