### ISSUE TITLE
ITMS-90338: Non-public API usage 

### ISSUE THREAD

**Issue by dfrobese** [kishikawakatsumi/KeychainAccess#473]
I'm using 4.1 by cocapods with Xcode 11.3.1, for an App running on Maccatalyst and iOS.
Distributing the app with iOS works fine, but for Maccatalyst the App-Store refuses the App with the follwing report. Any idea?
 
--
 
Dear Developer,We identified one or more issues with a recent delivery for your app,. Please correct the following issues, then upload again.ITMS-90338: Non-public API usage - The app references non-public symbols in Contents/Frameworks/KeychainAccess.framework/Versions/A/KeychainAccess: _SecAccessControlCreateWithFlags, _SecItemAdd, _SecItemCopyMatching, _SecItemDelete, _SecItemUpdate, _kSecAttrAccessControl, _kSecAttrAccessible, _kSecAttrAccessibleAfterFirstUnlock, _kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly, _kSecAttrAccessibleWhenPasscodeSetThisDeviceOnly, _kSecAttrAccessibleWhenUnlocked, _kSecAttrAccessibleWhenUnlockedThisDeviceOnly, _kSecAttrAccount, _kSecAttrAuthenticationType, _kSecAttrAuthenticationTypeDPA, _kSecAttrAuthenticationTypeDefault, _kSecAttrAuthenticationTypeHTMLForm, _kSecAttrAuthenticationTypeHTTPBasic, _kSecAttrAuthenticationTypeHTTPDigest, _kSecAttrAuthenticationTypeMSN, _kSecAttrAuthenticationTypeNTLM, _kSecAttrAuthenticationTypeRPA, _kSecAttrComment, _kSecAttrCreationDate, _kSecAttrCreator, _kSecAttrDescription, _kSecAttrGeneric, _kSecAttrIsInvisible, _kSecAttrIsNegative, _kSecAttrLabel, _kSecAttrModificationDate, _kSecAttrPath, _kSecAttrPort, _kSecAttrProtocol, _kSecAttrProtocolAFP, _kSecAttrProtocolAppleTalk, _kSecAttrProtocolDAAP, _kSecAttrProtocolEPPC, _kSecAttrProtocolFTP, _kSecAttrProtocolFTPAccount, _kSecAttrProtocolFTPProxy, _kSecAttrProtocolFTPS, _kSecAttrProtocolHTTP, _kSecAttrProtocolHTTPProxy, _kSecAttrProtocolHTTPS, _kSecAttrProtocolHTTPSProxy, _kSecAttrProtocolIMAP, _kSecAttrProtocolIMAPS, _kSecAttrProtocolIPP, _kSecAttrProtocolIRC, _kSecAttrProtocolIRCS, _kSecAttrProtocolLDAP, _kSecAttrProtocolLDAPS, _kSecAttrProtocolNNTP, _kSecAttrProtocolNNTPS, _kSecAttrProtocolPOP3, _kSecAttrProtocolPOP3S, _kSecAttrProtocolRTSP, _kSecAttrProtocolRTSPProxy, _kSecAttrProtocolSMB, _kSecAttrProtocolSMTP, _kSecAttrProtocolSOCKS, _kSecAttrProtocolSSH, _kSecAttrProtocolTelnet, _kSecAttrProtocolTelnetS, _kSecAttrSecurityDomain, _kSecAttrServer, _kSecAttrService, _kSecAttrSynchronizableAny, _kSecAttrType, _kSecClass, _kSecClassInternetPassword, _kSecMatchLimit, _kSecMatchLimitAll, _kSecMatchLimitOne, _kSecReturnAttributes, _kSecReturnData, _kSecReturnPersistentRef, _kSecReturnRef, _kSecUseAuthenticationContext, _kSecUseAuthenticationUI, _kSecUseAuthenticationUIFail, _kSecUseNoAuthenticationUI, _kSecValueData, _kSecValuePersistentRef, _kSecValueRef. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/Best regards,The App Store Team

**Comment by dfrobese** [comment]
Forget it, I've received a nice answer from Apple:

> Hello_ again, 
> 
> It turns out that the Private API isse was a temporary glitch on our end.
> We are expecting the issue resolved by today.
> 
> If you can submit again, the problem should be cleared._

**Comment by kishikawakatsumi** [comment]
@dfrobese Good to hear that. Thank you for letting me know right away 😄
