### ISSUE TITLE
Can't delete a key on macOS

### ISSUE THREAD

**Issue by houmie** [kishikawakatsumi/KeychainAccess#474]
I tried this:

`keychain["EMAIL"] = nil`

or this:

```
do {
       try keychain.remove("PASSWORD")
} catch let error {
       print("error: \(error)")
}
```

And I get this error:

```
OSStatus error:[-25244] Invalid attempt to change the owner of this item.

```

Using:

> KeychainAccess (4.1.0)

**Comment by kishikawakatsumi** [comment]
Can you share the code that you instantiate the keychain object?

**Comment by arvinkx** [comment]
Not sure if this is the reason you're experiencing this as well, but I was experiencing this issue when the service string I was initializing the Keychain with didn't match my app's bundle id.

**Comment by tegant** [comment]
Sorry for the late reply. I have found the reason. I had renamed my app's name (Target name). This caused the existing keys having a different owner name. Thanks

**Comment by houmie** [comment]
Sorry for the late reply. I have found the reason. I had renamed my app's name (Target name). This caused the existing keys having a different owner name. Thanks
