### ISSUE TITLE
How to solve NSOSStatusErrorDomain Code=-25293 failed to approve error?

### ISSUE THREAD

**Issue by appcornerit** [kishikawakatsumi/KeychainAccess#484]
Hi, 
I'm trying to figure out how to use associated domains for webcredentials, Keychain.requestSharedWebCredential from a real device with iOS 13.3.1 returns this error:
`NSOSStatusErrorDomain Code=-25293 MY_DOMAIN failed to approve MY_APP_ID.MY_APP_BUNDLE_ID `
Any experience how to solve this error?

**Comment by jarrodparkes** [comment]
@appcornerit were you able to figure this out?

**Comment by appcornerit** [comment]
I don't remember, it's too old.

**Comment by anushkmittal** [comment]
@jarrodparkes did u figure it out?

**Comment by jarrodparkes** [comment]
@anushkmittal I did not — I decided to abandon my attempt to auto populate the password field from shared web credentials. Note, I was able to get it to work from the "app's keychain".

Instead, I decided that as long as the iOS app was allowing the user to tap through to their password manager, then that was fine.

**Comment by dxhiOS** [comment]
> @anushkmittal I did not — I decided to abandon my attempt to auto populate the password field from shared web credentials. Note, I was able to get it to work from the "app's keychain".
> 
> Instead, I decided that as long as the iOS app was allowing the user to tap through to their password manager, then that was fine.

How did you do that? Is there any other way for users to allow their password manager？
