### ISSUE TITLE
Module stability since Swift 5.1

### ISSUE THREAD

**Issue by nick3389** [kishikawakatsumi/KeychainAccess#496]
Hello,

Since Swift 5.1 module stability is introduced for library compatibility for future releases of Swift. A `.swiftinterface` file is created which is actually the public header file for the library. To enable this, `BUILD_LIBRARY_FOR_DISTRIBUTION` must be activated in Build Settings. Is this something you have in mind or I can make a PR?

**Comment by kishikawakatsumi** [comment]
This library already enabled `BUILD_LIBRARY_FOR_DISTRIBUTION = YES`. 

See
https://github.com/kishikawakatsumi/KeychainAccess/blob/master/Lib/Configurations/KeychainAccess.xcconfig#L13

**Comment by nick3389** [comment]
@kishikawakatsumi There is a still warning for this in version 4.2.1. and in Pod project in XCode Build Library for Distribution is set to NO.

**Comment by kishikawakatsumi** [comment]
@nick3389 When installing the library via CocoaPods, the library is built from source code.
I don't think we need `BUILD_LIBRARY_FOR_DISTRIBUTION`, but why would you need it?

**Comment by nick3389** [comment]
@kishikawakatsumi There are just warnings from XCode that are just annoying. Also, I don't know if there will any issue in a future release of XCode.
