### ISSUE TITLE
The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99.

### ISSUE THREAD

**Issue by brandtdaniels** [kishikawakatsumi/KeychainAccess#500]
Receiving this warning for KeychainAccess when building

The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99.

**Comment by erginbilgin** [comment]
This is more of a CocoaPods issue on new Xcode 12 as far as I understand. Cocoapods will have official support of Xcode 12 with version 1.10. Until then you can set pods' minimum target version to 9 or above manually at build settings. 

Or add following to the end of your Podfile and hit pod install. It will set all pods target versions automatically to 12.0.

`post_install do |installer|
  installer.generated_projects.each do |project|
    project.build_configurations.each do |config|
        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 12.0
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
        end
    end
    project.targets.each do |target|
      target.build_configurations.each do |config|
        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 12.0
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
        end
      end
    end
  end
end
`

**Comment by klauslanza** [comment]
We are having this warning also using the SwiftPM way...

**Comment by bazscott** [comment]
Same, I'm using SPM

**Comment by Runrioter** [comment]
Check out this repo and make it local package, finally change from .iOS(.v8) to .iOS(.9) in `Package.swift` file

```diff
platforms: [
+        .macOS(.v10_10), .iOS(.v9), .tvOS(.v9), .watchOS(.v2)
-        .macOS(.v10_10), .iOS(.v8), .tvOS(.v9), .watchOS(.v2)
],
```

When fixing is released, then delete local package.

**Comment by klauslanza** [comment]
Ref: https://github.com/kishikawakatsumi/KeychainAccess/pull/490
