### ISSUE TITLE
ios unsupported deployment target warning

### ISSUE THREAD

**Issue by Peter-Schorn** [kishikawakatsumi/KeychainAccess#503]
As of Xcode 12, Apple bumped up the minimum deployment target for iOS from 8 to 9. Please update the `Package.swift` to reflect this so I don't get annoying compiler warnings
![Screen Shot 2020-09-19 at 2 18 26 AM](https://user-images.githubusercontent.com/58197311/93661573-680f0880-fa1e-11ea-929c-3fe491be6159.png)

**Comment by Runrioter** [comment]
@Peter-Schorn  Use the latest version v4.2.1

**Comment by kishikawakatsumi** [comment]
@Peter-Schorn @Runrioter 's answer is correct. It has resolved at v4.2.1. If you have still the same issue, feel free to reopen this issue.

**Comment by Peter-Schorn** [comment]
Thank you for the prompt response. After upgrading to 4.2.1, the issue has been resolved for me.
