### ISSUE TITLE
4.2.1 fails to install by Carthage

### ISSUE THREAD

**Issue by natalia-osa** [kishikawakatsumi/KeychainAccess#506]
The build fails when installed by Carthage with the newest Xcode. I suppose the problem is also indicated in the readme of the project because it says CI build is failing. It's probably the same issue, although I'm not sure. It's worth mentioning that if I compile it by hand, it's working properly.

Environment:
- macOS Catalina (10.15.6)
- carthage version 0.36.0
- Xcode 12.0 (12A7209) (and this version is set by xcode-select command)

The logs from `carthage update --platform iOS --no-use-binaries --use-ssh`
where Cartfile contains `github "kishikawakatsumi/KeychainAccess" == 4.2.1`
```
*** Building scheme "KeychainAccess" in KeychainAccess.xcworkspace
Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create /Users/MYUSERNAME/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/KeychainAccess/v4.2.1/Build/Intermediates.noindex/ArchiveIntermediates/KeychainAccess/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/KeychainAccess.framework/KeychainAccess /Users/MYUSERNAME/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/KeychainAccess/v4.2.1/Build/Products/Release-iphonesimulator/KeychainAccess.framework/KeychainAccess -output /Users/MYUSERNAME/Developer/MYAPPNAME/MYAPPNAME-ios/Carthage/Build/iOS/KeychainAccess.framework/KeychainAccess

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/k7/2pjm9vn53wlddpr_17n87stc0000gn/T/carthage-xcodebuild.xZGaNq.log
```

I'm also attaching the logs mentioned at the end of the console output (anonymized).
[Logs_annonym.log](https://github.com/kishikawakatsumi/KeychainAccess/files/5268479/Logs_annonym.log)

**Comment by kishikawakatsumi** [comment]
Carthage has a problem failing to build on Xcode 12.

Can you try this workaround? https://github.com/Carthage/Carthage/issues/3019#issuecomment-665136323

**Comment by natalia-osa** [comment]
I decided to migrate from Carthage to SPM after checking out this thread. Thanks for your support, I thought it was KeychainAccess issue while it was Carthage - sorry for troubling you!
