### ISSUE TITLE
Keychain iCloud

### ISSUE THREAD

**Issue by Droppix** [kishikawakatsumi/KeychainAccess#513]
Hi,

Is there any way to know, if the keychain cloud is disabled?
The problem is, if the user have 2 devices, one is Keychain cloud enabled and the other disabled (by forgetfulness during installation), the data will not be synchronized on the second device...and I would like to alert the user.

Thanks

**Comment by kishikawakatsumi** [comment]
By Keychain API, no. But you can check it by asking the ubiquity container URL to the file manager https://developer.apple.com/documentation/foundation/nsfilemanager/1408036-ubiquityidentitytoken .

See https://stackoverflow.com/a/7820137/1733883
