### ISSUE TITLE
M1 Mac Support

### ISSUE THREAD

**Issue by darkness51** [kishikawakatsumi/KeychainAccess#518]
Do you have plans to incorporate support for Apple Silicon simulator?

I am seeing this error and I assume is because the packages configuration establishes the supported platforms.

I may be wrong, but do you have some idea about how to fix it?

> Could not find module 'KeychainAccess' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator

**Comment by darkness51** [comment]
I just find out this works with Apple Silicon computer, but another dependency of my project is actually excluding `arm64` and `arm64e` and that's why the error above appears.

**Comment by xyzbilal** [comment]
how did you find out which dependency couses the problem. I have flutter project with widget extensions but cant work on simulator because of this issue.
