### ISSUE TITLE
No Build in XCODE 14.1

### ISSUE THREAD

**Issue by asan94** [kishikawakatsumi/KeychainAccess#550]
Module compiled with Swift 5.6.1 cannot be imported by the Swift 5.7.1

**Comment by kishikawakatsumi** [comment]
Please clean & rebuild if you are deploying this framework using SwiftPM, CocoaPods, or Carthage package managers. 

If you are using a pre-built binary, rebuild that binary with the latest compiler. But I don't provide pre-built binaries, so I don't think that's a possibility.
