### ISSUE TITLE
Any support of Privacy Manifest?

### ISSUE THREAD

**Issue by Anguschang582** [kishikawakatsumi/KeychainAccess#587]
Following definition of "third-party SDKs" that as mentioned in the WWDC23. and according to [Privacy manifest files | Apple Developer Documentation](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files), I believe this library may also require a Privacy Manifest for the upcoming app review in Spring 2024.

Do you have any plans to add a Privacy Manifest to this library?

Thank you very much!

**Comment by kishikawakatsumi** [comment]
This library does not track or collect privacy data and does not use the required reason API, so I do not believe a Privacy Manifest is necessary.

**Comment by kishikawakatsumi** [comment]
https://forums.developer.apple.com/forums/thread/746481
