### ISSUE TITLE
Support App Privacy Manifest 

### ISSUE THREAD

**Issue by ashwin-raghuraman** [kishikawakatsumi/KeychainAccess#596]
This repo needs to provide a privacy manifest, as described here: https://developer.apple.com/news/?id=av1nevon

![image](https://github.com/kishikawakatsumi/KeychainAccess/assets/95006842/bef472d6-c2b9-4673-9b35-a0bbce6f8173)

All this needs to be done by spring: https://developer.apple.com/news/?id=3d8a9yyh and  https://developer.apple.com/support/third-party-SDK-requirements/

Additionally any SDK that contains an app privacy manifest must be signed (xcframeworks)

We really need this, Thanks!

**Comment by kishikawakatsumi** [comment]
https://github.com/kishikawakatsumi/KeychainAccess/issues/589
