### ISSUE TITLE
iOS 7 Support 

### ISSUE THREAD

**Issue by switchCTRL** [kishikawakatsumi/KeychainAccess#63]
Is iOS 7 no longer supported?

**Comment by kishikawakatsumi** [comment]
No, if you use this library on iOS 7, add to your project manually.
Embedded framework requires iOS 8 or later.

See https://github.com/kishikawakatsumi/KeychainAccess/issues/29

**Comment by zeusent** [comment]
You should update the Readme file specifying this next to the CocoaPods installation method. Some people might be confused since a couple of lines before it is stated that iOS 7 is supported.
