### ISSUE TITLE
Build error on carthage update for swift-2.0 branch

### ISSUE THREAD

**Issue by rainypixels** [kishikawakatsumi/KeychainAccess#78]
I'm getting the following error when I try to run `carthage update` pointed at your swift-2.0 branch:

    *** Building scheme "KeychainAccess-iOS" in KeychainAccess.xcworkspace
    A shell task failed with exit code 65:
    ** BUILD FAILED **

    The following build commands failed:
	CompileSwift normal x86_64 /Users/n/Documents/Digest/digest_app_ios/DigestApp/Carthage/Checkouts/KeychainAccess/Lib/KeychainAccess/Keychain.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
    (2 failures)

    Segmentation fault: 11

Thoughts?

**Comment by mathiasnagler** [comment]
I am getting the same error.

**Comment by mathiasnagler** [comment]
I created a pull request with the necessary fixes so the project can be build using carthage. I suggest to keep this issue around or create a new one because disabling optimizations should only be a temporary workaround and should be reversed later on.

**Comment by kishikawakatsumi** [comment]
Fixed https://github.com/kishikawakatsumi/KeychainAccess/pull/80 Thank you very much for your reporting!!
