### ISSUE TITLE
Cannot compile by Xcode7 beta4.

### ISSUE THREAD

**Issue by sonsongithub** [kishikawakatsumi/KeychainAccess#88]
It cannot be compiled with a error "Cannot invoke 'takeUnretainedValue' with no arguments".
`takeUnretainedValue` 's arguments changed at beta4?

**Comment by kishikawakatsumi** [comment]
Fixed https://github.com/kishikawakatsumi/KeychainAccess/commit/7879a49b81c553ad9b40cbafda34a881648e2ff3

Thank you for your reporting! :pray:
