### ISSUE TITLE
git tag for swift-2.0 branch

### ISSUE THREAD

**Issue by dataich** [kishikawakatsumi/KeychainAccess#93]
Thank you for your great library.

I'd like you to tag like '2.0.0-beta.4'
Because I want to add dependency in *.podspec, but podspec doesn't allow symbols like `:git`, `:branch`.

can do this in Podfile.
```ruby
pod 'KeychainAccess', :git => 'https://github.com/kishikawakatsumi/KeychainAccess.git', :branch => 'swift-2.0'
```

cannot do this in *.podspec
```ruby
s.dependency 'KeychainAccess', :git => 'https://github.com/kishikawakatsumi/KeychainAccess.git', :branch => 'swift-2.0'
```

want
```ruby
s.dependency 'KeychainAccess', '~> 2.0.0-beta.4'
```

Best :smile:

**Comment by kishikawakatsumi** [comment]
Thank you very much for using my lib as dependency and the suggestion. There is no reason for opposing. I'll do later. Thanks!

**Comment by kishikawakatsumi** [comment]
Done! If you find any troubles, please let me know. Thanks! @dataich

**Comment by dataich** [comment]
Oh I'm sorry I let you misunderstand :bow: 

`s.version` in KeychainAccess.podspec should be same as git tag.

```ruby
Pod::Spec.new do |s|
  s.name             = "KeychainAccess"
  s.version          = "2.0.0-beta.6"
```
